/**
 * Unit tests for generate.ts — orchestrator that generates all recipe artifacts.
 *
 * Tests use a temporary directory to verify file generation without
 * affecting the committed generated/ directory.
 */

import { existsSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { ALL_RECIPES, generate } from "../generate";

const TMP_DIR = join(import.meta.dirname, "__tmp_generate_test__");

describe("generate", () => {
  beforeAll(() => {
    rmSync(TMP_DIR, { recursive: true, force: true });
  });

  afterAll(() => {
    rmSync(TMP_DIR, { recursive: true, force: true });
  });

  it("generates .css, .ts, and .d.ts for every recipe", () => {
    generate(TMP_DIR);

    for (const recipe of ALL_RECIPES) {
      const name = recipe.name;
      expect(existsSync(join(TMP_DIR, `${name}.css`))).toBe(true);
      expect(existsSync(join(TMP_DIR, `${name}.ts`))).toBe(true);
      expect(existsSync(join(TMP_DIR, `${name}.d.ts`))).toBe(true);
    }
  });

  it("generates all 19 recipes", () => {
    expect(ALL_RECIPES).toHaveLength(19);
  });

  it("generates spinner-geometry.ts", () => {
    expect(existsSync(join(TMP_DIR, "spinner-geometry.ts"))).toBe(true);

    const content = readFileSync(join(TMP_DIR, "spinner-geometry.ts"), "utf-8");
    expect(content).toContain("export interface SpinnerGeometry");
    expect(content).toContain("export type SpinnerSize =");
    expect(content).toContain("export const SPINNER_GEOMETRY");
    expect(content).toContain("export function getSpinnerGeometry");
  });

  it("generates CSS files with header comment", () => {
    const css = readFileSync(join(TMP_DIR, "button.css"), "utf-8");
    expect(css).toMatch(/^\/\* Generated by @cocso-ui\/codegen/);
  });

  it("generates runtime files with className function", () => {
    const runtime = readFileSync(join(TMP_DIR, "button.ts"), "utf-8");
    expect(runtime).toContain("export function button(");
    expect(runtime).toContain("ButtonVariantProps");
  });

  it("generates type declaration files", () => {
    const types = readFileSync(join(TMP_DIR, "button.d.ts"), "utf-8");
    expect(types).toContain("export interface ButtonVariantProps");
    expect(types).toContain("export declare function button(");
  });

  it("spinner-geometry contains all spinner sizes", () => {
    const content = readFileSync(join(TMP_DIR, "spinner-geometry.ts"), "utf-8");
    const sizes = Object.keys(
      (ALL_RECIPES.find((r) => r.name === "spinner")!).variants.size as Record<string, unknown>
    );
    for (const size of sizes) {
      expect(content).toContain(`"${size}"`);
    }
  });
});
