/**
 * Unit tests for generate-recipe.ts — CSS, runtime, and type generation.
 *
 * Tests the core codegen functions with minimal recipe fixtures
 * to cover branches not exercised by the parity test.
 */

import { defineRecipe } from "@cocso-ui/recipe";
import { describe, expect, it } from "vitest";
import {
  generateCSS,
  generateRuntime,
  generateTypes,
  getAllCombinations,
} from "../generate-recipe";

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const simpleRecipe = defineRecipe({
  name: "test-btn",
  slots: ["root"] as const,
  variants: {
    variant: {
      primary: { root: { bgColor: "primary-950", fontColor: "white" } },
      secondary: { root: { bgColor: "neutral-100" } },
    },
    size: {
      sm: { root: { height: 28, paddingInline: 8 } },
      md: { root: { height: 36, paddingInline: 12 } },
    },
  },
  defaultVariants: { variant: "primary", size: "md" },
  base: {
    root: { fontWeight: "semibold" },
  },
});

const compoundRecipe = defineRecipe({
  name: "test-compound",
  slots: ["root"] as const,
  variants: {
    shape: {
      square: { root: {} },
      circle: { root: { borderRadius: "100%" } },
    },
    size: {
      sm: { root: { height: 24 } },
      md: { root: { height: 32 } },
      lg: { root: { height: 48 } },
    },
  },
  compoundVariants: [
    {
      conditions: { shape: "square", size: ["sm", "md"] },
      styles: { root: { borderRadius: "radius-2" } },
    },
    {
      conditions: { shape: "square", size: "lg" },
      styles: { root: { borderRadius: "radius-4" } },
    },
  ],
  defaultVariants: { shape: "square", size: "md" },
});

const stateRecipe = defineRecipe({
  name: "test-state",
  slots: ["root"] as const,
  variants: {
    variant: {
      primary: { root: { bgColor: "primary-950" } },
      danger: { root: { bgColor: "danger-500" } },
    },
  },
  states: {
    hover: {
      variant: {
        primary: { root: { bgColor: "primary-800" } },
        danger: { root: { bgColor: "danger-600" } },
      },
    },
    active: {
      variant: {
        primary: { root: { bgColor: "primary-700" } },
      },
    },
  },
  defaultVariants: { variant: "primary" },
});

const noDefaultRecipe = defineRecipe({
  name: "test-nodfl",
  slots: ["root"] as const,
  variants: {
    status: {
      success: { root: { bgColor: "success-500" } },
      error: { root: { bgColor: "danger-500" } },
    },
  },
});

// ---------------------------------------------------------------------------
// getAllCombinations
// ---------------------------------------------------------------------------

describe("getAllCombinations", () => {
  it("returns all variant combinations", () => {
    const combos = getAllCombinations(simpleRecipe);
    expect(combos).toHaveLength(4); // 2 variants × 2 sizes
    expect(combos).toContainEqual({ variant: "primary", size: "sm" });
    expect(combos).toContainEqual({ variant: "primary", size: "md" });
    expect(combos).toContainEqual({ variant: "secondary", size: "sm" });
    expect(combos).toContainEqual({ variant: "secondary", size: "md" });
  });

  it("returns all combinations for compound recipe", () => {
    const combos = getAllCombinations(compoundRecipe);
    expect(combos).toHaveLength(6); // 2 shapes × 3 sizes
  });
});

// ---------------------------------------------------------------------------
// generateCSS
// ---------------------------------------------------------------------------

describe("generateCSS", () => {
  it("generates header comment", () => {
    const css = generateCSS(simpleRecipe);
    expect(css).toMatch(/^\/\* Generated by @cocso-ui\/codegen/);
  });

  it("generates base styles", () => {
    const css = generateCSS(simpleRecipe);
    expect(css).toContain(".cocso-test-btn {");
    expect(css).toContain("--cocso-test-btn-font-weight: 600;");
  });

  it("generates per-dimension variant rules", () => {
    const css = generateCSS(simpleRecipe);
    expect(css).toContain(
      ".cocso-test-btn.cocso-test-btn--variant-primary {"
    );
    expect(css).toContain(
      "--cocso-test-btn-bg-color: var(--cocso-color-primary-950);"
    );
    expect(css).toContain(
      ".cocso-test-btn.cocso-test-btn--size-sm {"
    );
    expect(css).toContain("--cocso-test-btn-height: 28px;");
  });

  it("generates compound variant rules with array expansion", () => {
    const css = generateCSS(compoundRecipe);
    // Array condition { size: ["sm", "md"] } should expand to 2 selectors
    expect(css).toContain(
      ".cocso-test-compound.cocso-test-compound--shape-square.cocso-test-compound--size-sm {"
    );
    expect(css).toContain(
      ".cocso-test-compound.cocso-test-compound--shape-square.cocso-test-compound--size-md {"
    );
    expect(css).toContain(
      ".cocso-test-compound.cocso-test-compound--shape-square.cocso-test-compound--size-lg {"
    );
  });

  it("generates state-suffixed properties", () => {
    const css = generateCSS(stateRecipe);
    expect(css).toContain("--cocso-test-state-bg-color-hover:");
    expect(css).toContain("--cocso-test-state-bg-color-active:");
    // hover state for primary variant
    expect(css).toContain(
      "--cocso-test-state-bg-color-hover: var(--cocso-color-primary-800);"
    );
    // hover state for danger variant
    expect(css).toContain(
      "--cocso-test-state-bg-color-hover: var(--cocso-color-danger-600);"
    );
    // active state for primary variant
    expect(css).toContain(
      "--cocso-test-state-bg-color-active: var(--cocso-color-primary-700);"
    );
  });

  it("merges duplicate selectors", () => {
    const css = generateCSS(stateRecipe);
    // The primary variant should appear once with both base and state properties merged
    const matches = css.match(
      /\.cocso-test-state\.cocso-test-state--variant-primary \{/g
    );
    // Base + hover + active on same selector → should be merged into one block
    expect(matches).not.toBeNull();
    expect(matches!.length).toBe(1);
  });

  it("handles recipe with no base styles", () => {
    const css = generateCSS(noDefaultRecipe);
    // Should not have a bare .cocso-test-nodfl {} block
    expect(css).not.toMatch(/^\.cocso-test-nodfl \{/m);
    expect(css).toContain(".cocso-test-nodfl.cocso-test-nodfl--status-success {");
  });
});

// ---------------------------------------------------------------------------
// generateRuntime
// ---------------------------------------------------------------------------

describe("generateRuntime", () => {
  it("generates a className function", () => {
    const runtime = generateRuntime(simpleRecipe);
    expect(runtime).toContain("export function testBtn(");
    expect(runtime).toContain("TestBtnVariantProps");
  });

  it("includes default values in destructuring", () => {
    const runtime = generateRuntime(simpleRecipe);
    expect(runtime).toContain('variant = "primary"');
    expect(runtime).toContain('size = "md"');
  });

  it("generates className array with BEM classes", () => {
    const runtime = generateRuntime(simpleRecipe);
    expect(runtime).toContain('"cocso-test-btn"');
    expect(runtime).toContain("cocso-test-btn--variant-");
    expect(runtime).toContain("cocso-test-btn--size-");
  });

  it("generates interface with optional props when defaults exist", () => {
    const runtime = generateRuntime(simpleRecipe);
    expect(runtime).toContain("variant?:");
    expect(runtime).toContain("size?:");
  });

  it("generates required props when no defaults", () => {
    const runtime = generateRuntime(noDefaultRecipe);
    // No defaultVariants → props should not have ?
    expect(runtime).toMatch(/status\??: "success" \| "error"/);
  });

  it("throws on multi-slot recipe", () => {
    const multiSlot = defineRecipe({
      name: "multi",
      slots: ["root", "label"] as const,
      variants: {
        size: { sm: { root: {} } },
      },
    });
    expect(() => generateRuntime(multiSlot)).toThrow(
      /Multi-slot runtime generation not yet implemented/
    );
  });

  it("handles kebab-case recipe names", () => {
    const runtime = generateRuntime(stateRecipe);
    // "test-state" → function testState, interface TestStateVariantProps
    expect(runtime).toContain("export function testState(");
    expect(runtime).toContain("TestStateVariantProps");
  });
});

// ---------------------------------------------------------------------------
// generateTypes
// ---------------------------------------------------------------------------

describe("generateTypes", () => {
  it("generates TypeScript interface", () => {
    const types = generateTypes(simpleRecipe);
    expect(types).toContain("export interface TestBtnVariantProps {");
    expect(types).toContain('variant?: "primary" | "secondary"');
    expect(types).toContain('size?: "sm" | "md"');
  });

  it("generates individual type aliases per dimension", () => {
    const types = generateTypes(simpleRecipe);
    expect(types).toContain(
      'export type TestBtnVariant = "primary" | "secondary";'
    );
    expect(types).toContain('export type TestBtnSize = "sm" | "md";');
  });

  it("generates function declaration", () => {
    const types = generateTypes(simpleRecipe);
    expect(types).toContain(
      "export declare function testBtn(props?: TestBtnVariantProps): string;"
    );
  });

  it("throws on multi-slot recipe", () => {
    const multiSlot = defineRecipe({
      name: "multi",
      slots: ["root", "label"] as const,
      variants: {
        size: { sm: { root: {} } },
      },
    });
    expect(() => generateTypes(multiSlot)).toThrow(
      /Multi-slot type generation not yet implemented/
    );
  });

  it("generates header comment", () => {
    const types = generateTypes(simpleRecipe);
    expect(types).toMatch(/^\/\* Generated by @cocso-ui\/codegen/);
  });

  it("handles recipe with no default variants", () => {
    const types = generateTypes(noDefaultRecipe);
    // Without defaults, the status field should still be typed
    expect(types).toContain('status');
    expect(types).toContain('"success" | "error"');
  });
});
