// Generated by @cocso-ui/codegen — do not edit.
// Source: packages/recipe/src/recipes
// Regenerate: pnpm --filter @cocso-ui/codegen generate:mobile

import SwiftUI

public enum CCAlertVariant: String, CaseIterable, Sendable {
    case info
    case success
    case warning
    case error
}

public struct CCAlertStyle: Equatable, Sendable {
    public var borderRadius: CGFloat?
    public var paddingX: CGFloat?
    public var paddingY: CGFloat?
    public var fontSize: CGFloat?
    public var bgColor: SwiftUI.Color?
    public var fontColor: SwiftUI.Color?
    public var borderColor: SwiftUI.Color?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCAlertVariant,
        scheme: ColorScheme
    ) -> CCAlertStyle {
        var style = CCAlertStyle()
        style.borderRadius = CocsoTokens.Radius.r4
        style.paddingX = 16
        style.paddingY = 12
        style.fontSize = 14
        if variant == .info {
            style.bgColor = CocsoTokens.Color.feedbackInfoSubtle(scheme)
            style.fontColor = CocsoTokens.Color.feedbackInfoText(scheme)
            style.borderColor = CocsoTokens.Color.feedbackInfoBorder(scheme)
        }
        if variant == .success {
            style.bgColor = CocsoTokens.Color.feedbackSuccessSubtle(scheme)
            style.fontColor = CocsoTokens.Color.feedbackSuccessText(scheme)
            style.borderColor = CocsoTokens.Color.feedbackSuccessBorder(scheme)
        }
        if variant == .warning {
            style.bgColor = CocsoTokens.Color.feedbackWarningSubtle(scheme)
            style.fontColor = CocsoTokens.Color.feedbackWarningText(scheme)
            style.borderColor = CocsoTokens.Color.feedbackWarningBorder(scheme)
        }
        if variant == .error {
            style.bgColor = CocsoTokens.Color.feedbackDangerSubtle(scheme)
            style.fontColor = CocsoTokens.Color.feedbackDangerText(scheme)
            style.borderColor = CocsoTokens.Color.feedbackDangerBorder(scheme)
        }
        return style
    }
}

public enum CCAvatarSize: String, CaseIterable, Sendable {
    case xs
    case sm
    case md
    case lg
    case xl
}

public enum CCAvatarShape: String, CaseIterable, Sendable {
    case circle
    case square
}

public struct CCAvatarStyle: Equatable, Sendable {
    public var bgColor: SwiftUI.Color?
    public var fontColor: SwiftUI.Color?
    public var fontWeight: Font.Weight?
    public var height: CGFloat?
    public var width: CGFloat?
    public var fontSize: CGFloat?
    public var borderRadiusFull: Bool?
    public var borderRadius: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        size: CCAvatarSize,
        shape: CCAvatarShape,
        scheme: ColorScheme
    ) -> CCAvatarStyle {
        var style = CCAvatarStyle()
        style.bgColor = CocsoTokens.Color.surfaceNeutral(scheme)
        style.fontColor = CocsoTokens.Color.textPrimary(scheme)
        style.fontWeight = .medium
        if size == .xs {
            style.height = 24
            style.width = 24
            style.fontSize = 10
        }
        if size == .sm {
            style.height = 32
            style.width = 32
            style.fontSize = 12
        }
        if size == .md {
            style.height = 40
            style.width = 40
            style.fontSize = 14
        }
        if size == .lg {
            style.height = 48
            style.width = 48
            style.fontSize = 16
        }
        if size == .xl {
            style.height = 64
            style.width = 64
            style.fontSize = 20
        }
        if shape == .circle {
            style.borderRadiusFull = true
        }
        if shape == .square && size == .xs {
            style.borderRadius = CocsoTokens.Radius.r2
        }
        if shape == .square && size == .sm {
            style.borderRadius = CocsoTokens.Radius.r3
        }
        if shape == .square && size == .md {
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if shape == .square && size == .lg {
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if shape == .square && size == .xl {
            style.borderRadius = CocsoTokens.Radius.r5
        }
        return style
    }
}

public enum CCBadgeVariant: String, CaseIterable, Sendable {
    case primary
    case primarySubtle
    case secondary
    case success
    case error
    case warning
    case info
    case outline
}

public enum CCBadgeSize: String, CaseIterable, Sendable {
    case large
    case medium
    case small
}

public enum CCBadgeShape: String, CaseIterable, Sendable {
    case square
    case circle
    case rounded
}

public struct CCBadgeStyle: Equatable, Sendable {
    public var bgColor: SwiftUI.Color?
    public var fontColor: SwiftUI.Color?
    public var paddingX: CGFloat?
    public var paddingY: CGFloat?
    public var fontSize: CGFloat?
    public var borderRadiusFull: Bool?
    public var borderRadius: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCBadgeVariant,
        size: CCBadgeSize,
        shape: CCBadgeShape,
        scheme: ColorScheme
    ) -> CCBadgeStyle {
        var style = CCBadgeStyle()
        if variant == .primary {
            style.bgColor = CocsoTokens.Color.interactivePrimary(scheme)
            style.fontColor = CocsoTokens.Color.textOnPrimary(scheme)
        }
        if variant == .primarySubtle {
            style.bgColor = CocsoTokens.Color.interactivePrimarySubtle(scheme)
            style.fontColor = CocsoTokens.Color.interactivePrimaryText(scheme)
        }
        if variant == .secondary {
            style.bgColor = CocsoTokens.Color.surfaceSecondary(scheme)
            style.fontColor = CocsoTokens.Color.textSecondary(scheme)
        }
        if variant == .success {
            style.bgColor = CocsoTokens.Color.feedbackSuccessSubtle(scheme)
            style.fontColor = CocsoTokens.Color.feedbackSuccessText(scheme)
        }
        if variant == .error {
            style.bgColor = CocsoTokens.Color.feedbackDangerSubtle(scheme)
            style.fontColor = CocsoTokens.Color.feedbackDangerText(scheme)
        }
        if variant == .warning {
            style.bgColor = CocsoTokens.Color.feedbackWarningSubtle(scheme)
            style.fontColor = CocsoTokens.Color.feedbackWarningText(scheme)
        }
        if variant == .info {
            style.bgColor = CocsoTokens.Color.feedbackInfoSubtle(scheme)
            style.fontColor = CocsoTokens.Color.feedbackInfoText(scheme)
        }
        if variant == .outline {
            style.fontColor = CocsoTokens.Color.textPrimary(scheme)
        }
        if size == .large {
            style.paddingX = 10
            style.paddingY = 5
            style.fontSize = 14
        }
        if size == .medium {
            style.paddingX = 8
            style.paddingY = 4
            style.fontSize = 12
        }
        if size == .small {
            style.paddingX = 6
            style.paddingY = 3
            style.fontSize = 11
        }
        if shape == .circle {
            style.borderRadiusFull = true
        }
        if shape == .rounded {
            style.borderRadius = CocsoTokens.Radius.full
        }
        if shape == .square && size == .small {
            style.borderRadius = CocsoTokens.Radius.r3
        }
        if shape == .square && size == .large {
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if shape == .square && size == .medium {
            style.borderRadius = CocsoTokens.Radius.r4
        }
        return style
    }
}

public enum CCBreadcrumbSize: String, CaseIterable, Sendable {
    case sm
    case md
    case lg
}

public struct CCBreadcrumbStyle: Equatable, Sendable {
    public var fontColor: SwiftUI.Color?
    public var fontSize: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        size: CCBreadcrumbSize,
        scheme: ColorScheme
    ) -> CCBreadcrumbStyle {
        var style = CCBreadcrumbStyle()
        style.fontColor = CocsoTokens.Color.textSecondary(scheme)
        if size == .sm {
            style.fontSize = 12
        }
        if size == .md {
            style.fontSize = 14
        }
        if size == .lg {
            style.fontSize = 16
        }
        return style
    }
}

public enum CCButtonVariant: String, CaseIterable, Sendable {
    case primary
    case secondary
    case outline
    case ghost
    case success
    case error
    case warning
    case info
    case neutral
    case errorGhost
}

public enum CCButtonSize: String, CaseIterable, Sendable {
    case xLarge
    case large
    case medium
    case small
    case xSmall
}

public enum CCButtonShape: String, CaseIterable, Sendable {
    case square
    case circle
    case rounded
    case sharp
}

public enum CCButtonAlign: String, CaseIterable, Sendable {
    case center
    case start
    case between
}

public struct CCButtonStyle: Equatable, Sendable {
    public var bgColor: SwiftUI.Color?
    public var fontColor: SwiftUI.Color?
    public var height: CGFloat?
    public var paddingInline: CGFloat?
    public var contentPaddingX: CGFloat?
    public var contentPaddingY: CGFloat?
    public var fontSize: CGFloat?
    public var borderRadiusFull: Bool?
    public var borderRadius: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCButtonVariant,
        size: CCButtonSize,
        shape: CCButtonShape,
        align: CCButtonAlign,
        scheme: ColorScheme
    ) -> CCButtonStyle {
        var style = CCButtonStyle()
        if variant == .primary {
            style.bgColor = CocsoTokens.Color.interactivePrimary(scheme)
            style.fontColor = CocsoTokens.Color.textOnPrimary(scheme)
        }
        if variant == .secondary {
            style.bgColor = CocsoTokens.Color.surfaceSecondary(scheme)
            style.fontColor = CocsoTokens.Color.textSecondary(scheme)
        }
        if variant == .outline {
            style.fontColor = CocsoTokens.Color.textPrimary(scheme)
        }
        if variant == .ghost {
            style.bgColor = CocsoTokens.Color.surfacePrimary(scheme)
            style.fontColor = CocsoTokens.Color.textPrimary(scheme)
        }
        if variant == .success {
            style.bgColor = CocsoTokens.Color.interactiveSuccess(scheme)
            style.fontColor = CocsoTokens.Color.textOnSuccess(scheme)
        }
        if variant == .error {
            style.bgColor = CocsoTokens.Color.interactiveDanger(scheme)
            style.fontColor = CocsoTokens.Color.textOnDanger(scheme)
        }
        if variant == .warning {
            style.bgColor = CocsoTokens.Color.interactiveWarning(scheme)
            style.fontColor = CocsoTokens.Color.textOnWarning(scheme)
        }
        if variant == .info {
            style.bgColor = CocsoTokens.Color.interactiveInfo(scheme)
            style.fontColor = CocsoTokens.Color.textOnInfo(scheme)
        }
        if variant == .neutral {
            style.bgColor = CocsoTokens.Color.interactiveNeutral(scheme)
            style.fontColor = CocsoTokens.Color.textPrimary(scheme)
        }
        if variant == .errorGhost {
            style.fontColor = CocsoTokens.Color.feedbackDangerText(scheme)
        }
        if size == .xLarge {
            style.height = 56
            style.paddingInline = 16
            style.contentPaddingX = 6
            style.contentPaddingY = 0
            style.fontSize = 16
        }
        if size == .large {
            style.height = 40
            style.paddingInline = 14
            style.contentPaddingX = 6
            style.contentPaddingY = 0
            style.fontSize = 14
        }
        if size == .medium {
            style.height = 36
            style.paddingInline = 12
            style.contentPaddingX = 6
            style.contentPaddingY = 0
            style.fontSize = 14
        }
        if size == .small {
            style.height = 32
            style.paddingInline = 10
            style.contentPaddingX = 2
            style.contentPaddingY = 0
            style.fontSize = 14
        }
        if size == .xSmall {
            style.height = 28
            style.paddingInline = 8
            style.contentPaddingX = 0
            style.contentPaddingY = 0
            style.fontSize = 12
        }
        if shape == .circle {
            style.borderRadiusFull = true
        }
        if shape == .rounded {
            style.borderRadius = CocsoTokens.Radius.full
        }
        if shape == .sharp {
            style.borderRadius = 0
        }
        if shape == .square && size == .xSmall {
            style.borderRadius = CocsoTokens.Radius.r3
        }
        if shape == .square && size == .large {
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if shape == .square && size == .medium {
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if shape == .square && size == .small {
            style.borderRadius = CocsoTokens.Radius.r4
        }
        return style
    }
}

public enum CCCardVariant: String, CaseIterable, Sendable {
    case elevated
    case outlined
    case filled
}

public enum CCCardPadding: String, CaseIterable, Sendable {
    case sm
    case md
    case lg
}

public struct CCCardStyle: Equatable, Sendable {
    public var bgColor: SwiftUI.Color?
    public var borderRadius: CGFloat?
    public var paddingX: CGFloat?
    public var paddingY: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCCardVariant,
        padding: CCCardPadding,
        scheme: ColorScheme
    ) -> CCCardStyle {
        var style = CCCardStyle()
        if variant == .elevated {
            style.bgColor = CocsoTokens.Color.surfacePrimary(scheme)
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if variant == .outlined {
            style.bgColor = CocsoTokens.Color.surfacePrimary(scheme)
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if variant == .filled {
            style.bgColor = CocsoTokens.Color.surfaceSecondary(scheme)
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if padding == .sm {
            style.paddingX = 12
            style.paddingY = 12
        }
        if padding == .md {
            style.paddingX = 16
            style.paddingY = 16
        }
        if padding == .lg {
            style.paddingX = 24
            style.paddingY = 24
        }
        return style
    }
}

public enum CCCheckboxSize: String, CaseIterable, Sendable {
    case large
    case medium
    case small
}

public enum CCCheckboxStatus: String, CaseIterable, Sendable {
    case on
    case off
    case intermediate
}

public struct CCCheckboxStyle: Equatable, Sendable {
    public var focusRingColor: SwiftUI.Color?
    public var size: CGFloat?
    public var radius: CGFloat?
    public var borderColor: SwiftUI.Color?
    public var bgColor: SwiftUI.Color?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        size: CCCheckboxSize,
        status: CCCheckboxStatus,
        scheme: ColorScheme
    ) -> CCCheckboxStyle {
        var style = CCCheckboxStyle()
        style.focusRingColor = CocsoTokens.Color.focusRing(scheme)
        if size == .large {
            style.size = 18
            style.radius = CocsoTokens.Radius.r3
        }
        if size == .medium {
            style.size = 16
            style.radius = CocsoTokens.Radius.r2
        }
        if size == .small {
            style.size = 14
            style.radius = CocsoTokens.Radius.r1
        }
        if status == .on {
            style.borderColor = CocsoTokens.Color.interactivePrimary(scheme)
            style.bgColor = CocsoTokens.Color.interactivePrimary(scheme)
        }
        if status == .off {
            style.borderColor = CocsoTokens.Color.borderStrong(scheme)
            style.bgColor = CocsoTokens.Color.surfacePrimary(scheme)
        }
        if status == .intermediate {
            style.borderColor = CocsoTokens.Color.interactivePrimary(scheme)
            style.bgColor = CocsoTokens.Color.interactivePrimary(scheme)
        }
        return style
    }
}

public enum CCDialogSize: String, CaseIterable, Sendable {
    case small
    case medium
    case large
}

public struct CCDialogStyle: Equatable, Sendable {
    public var bgColor: SwiftUI.Color?
    public var borderRadius: CGFloat?
    public var paddingTop: CGFloat?
    public var paddingBottom: CGFloat?
    public var paddingLeft: CGFloat?
    public var paddingRight: CGFloat?
    public var width: CGFloat?
    public var height: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        size: CCDialogSize,
        scheme: ColorScheme
    ) -> CCDialogStyle {
        var style = CCDialogStyle()
        style.bgColor = CocsoTokens.Color.surfacePrimary(scheme)
        style.borderRadius = CocsoTokens.Radius.r5
        style.paddingTop = 20
        style.paddingBottom = 20
        style.paddingLeft = 20
        style.paddingRight = 20
        if size == .small {
            style.width = 380
            style.height = 200
        }
        if size == .medium {
            style.width = 520
            style.height = 260
        }
        if size == .large {
            style.width = 680
            style.height = 340
        }
        return style
    }
}

public enum CCInputSize: String, CaseIterable, Sendable {
    case xSmall
    case small
    case medium
    case large
}

public struct CCInputStyle: Equatable, Sendable {
    public var borderColor: SwiftUI.Color?
    public var height: CGFloat?
    public var paddingX: CGFloat?
    public var fontSize: CGFloat?
    public var borderRadius: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        size: CCInputSize,
        scheme: ColorScheme
    ) -> CCInputStyle {
        var style = CCInputStyle()
        style.borderColor = CocsoTokens.Color.borderPrimary(scheme)
        if size == .xSmall {
            style.height = 28
            style.paddingX = 8
            style.fontSize = 12
            style.borderRadius = CocsoTokens.Radius.r3
        }
        if size == .small {
            style.height = 32
            style.paddingX = 10
            style.fontSize = 12
            style.borderRadius = CocsoTokens.Radius.r3
        }
        if size == .medium {
            style.height = 36
            style.paddingX = 12
            style.fontSize = 14
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if size == .large {
            style.height = 40
            style.paddingX = 14
            style.fontSize = 14
            style.borderRadius = CocsoTokens.Radius.r4
        }
        return style
    }
}

public enum CCLinkVariant: String, CaseIterable, Sendable {
    case inline
    case current
    case plain
}

public struct CCLinkStyle: Equatable, Sendable {
    public var color: SwiftUI.Color?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCLinkVariant,
        scheme: ColorScheme
    ) -> CCLinkStyle {
        var style = CCLinkStyle()
        if variant == .inline {
            style.color = CocsoTokens.Color.interactiveInfoText(scheme)
        }
        if variant == .plain {
            style.color = CocsoTokens.Color.interactiveInfoText(scheme)
        }
        return style
    }
}

public enum CCPaginationPageState: String, CaseIterable, Sendable {
    case active
    case inactive
    case disabled
}

public struct CCPaginationStyle: Equatable, Sendable {
    public var height: CGFloat?
    public var width: CGFloat?
    public var borderRadius: CGFloat?
    public var fontSize: CGFloat?
    public var bgColor: SwiftUI.Color?
    public var fontColor: SwiftUI.Color?
    public var fontWeight: Font.Weight?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        pageState: CCPaginationPageState,
        scheme: ColorScheme
    ) -> CCPaginationStyle {
        var style = CCPaginationStyle()
        style.height = 32
        style.width = 32
        style.borderRadius = CocsoTokens.Radius.r4
        style.fontSize = 14
        if pageState == .active {
            style.bgColor = CocsoTokens.Color.interactivePrimary(scheme)
            style.fontColor = CocsoTokens.Color.textOnPrimary(scheme)
            style.fontWeight = .semibold
        }
        if pageState == .inactive {
            style.fontColor = CocsoTokens.Color.textPrimary(scheme)
        }
        if pageState == .disabled {
            style.fontColor = CocsoTokens.Color.textDisabled(scheme)
        }
        return style
    }
}

public enum CCProgressVariant: String, CaseIterable, Sendable {
    case primary
    case secondary
    case success
    case danger
    case warning
    case info
}

public enum CCProgressSize: String, CaseIterable, Sendable {
    case sm
    case md
    case lg
}

public struct CCProgressStyle: Equatable, Sendable {
    public var bgColor: SwiftUI.Color?
    public var fillColor: SwiftUI.Color?
    public var height: CGFloat?
    public var borderRadius: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCProgressVariant,
        size: CCProgressSize,
        scheme: ColorScheme
    ) -> CCProgressStyle {
        var style = CCProgressStyle()
        style.bgColor = CocsoTokens.Color.surfaceNeutral(scheme)
        if variant == .primary {
            style.fillColor = CocsoTokens.Color.interactivePrimary(scheme)
        }
        if variant == .secondary {
            style.fillColor = CocsoTokens.Color.textMuted(scheme)
        }
        if variant == .success {
            style.fillColor = CocsoTokens.Color.feedbackSuccess(scheme)
        }
        if variant == .danger {
            style.fillColor = CocsoTokens.Color.feedbackDanger(scheme)
        }
        if variant == .warning {
            style.fillColor = CocsoTokens.Color.feedbackWarning(scheme)
        }
        if variant == .info {
            style.fillColor = CocsoTokens.Color.feedbackInfo(scheme)
        }
        if size == .sm {
            style.height = 4
            style.borderRadius = CocsoTokens.Radius.r1
        }
        if size == .md {
            style.height = 8
            style.borderRadius = CocsoTokens.Radius.r2
        }
        if size == .lg {
            style.height = 12
            style.borderRadius = CocsoTokens.Radius.r3
        }
        return style
    }
}

public enum CCRadioSize: String, CaseIterable, Sendable {
    case large
    case medium
    case small
}

public enum CCRadioSelected: String, CaseIterable, Sendable {
    case `true`
    case `false`
}

public struct CCRadioStyle: Equatable, Sendable {
    public var bgColor: SwiftUI.Color?
    public var borderColor: SwiftUI.Color?
    public var checkedColor: SwiftUI.Color?
    public var focusRingColor: SwiftUI.Color?
    public var size: CGFloat?
    public var dotSize: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        size: CCRadioSize,
        selected: CCRadioSelected,
        scheme: ColorScheme
    ) -> CCRadioStyle {
        var style = CCRadioStyle()
        style.bgColor = CocsoTokens.Color.surfacePrimary(scheme)
        style.borderColor = CocsoTokens.Color.textPrimary(scheme)
        style.checkedColor = CocsoTokens.Color.interactivePrimary(scheme)
        style.focusRingColor = CocsoTokens.Color.focusRing(scheme)
        if size == .large {
            style.size = 18
            style.dotSize = 8
        }
        if size == .medium {
            style.size = 16
            style.dotSize = 7
        }
        if size == .small {
            style.size = 14
            style.dotSize = 6
        }
        if selected == .`true` {
            style.bgColor = CocsoTokens.Color.interactivePrimary(scheme)
            style.borderColor = CocsoTokens.Color.interactivePrimary(scheme)
        }
        if selected == .`false` {
            style.bgColor = CocsoTokens.Color.surfacePrimary(scheme)
            style.borderColor = CocsoTokens.Color.borderStrong(scheme)
        }
        return style
    }
}

public enum CCSelectSize: String, CaseIterable, Sendable {
    case xSmall
    case small
    case medium
    case large
}

public struct CCSelectStyle: Equatable, Sendable {
    public var borderColor: SwiftUI.Color?
    public var minWidth: CGFloat?
    public var height: CGFloat?
    public var paddingLeft: CGFloat?
    public var paddingRight: CGFloat?
    public var iconRight: CGFloat?
    public var fontSize: CGFloat?
    public var borderRadius: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        size: CCSelectSize,
        scheme: ColorScheme
    ) -> CCSelectStyle {
        var style = CCSelectStyle()
        style.borderColor = CocsoTokens.Color.borderPrimary(scheme)
        if size == .xSmall {
            style.minWidth = 28
            style.height = 28
            style.paddingLeft = 8
            style.paddingRight = 26
            style.iconRight = 8
            style.fontSize = 12
            style.borderRadius = CocsoTokens.Radius.r3
        }
        if size == .small {
            style.minWidth = 32
            style.height = 32
            style.paddingLeft = 10
            style.paddingRight = 32
            style.iconRight = 10
            style.fontSize = 12
            style.borderRadius = CocsoTokens.Radius.r3
        }
        if size == .medium {
            style.minWidth = 36
            style.height = 36
            style.paddingLeft = 12
            style.paddingRight = 38
            style.iconRight = 12
            style.fontSize = 14
            style.borderRadius = CocsoTokens.Radius.r4
        }
        if size == .large {
            style.minWidth = 40
            style.height = 40
            style.paddingLeft = 14
            style.paddingRight = 42
            style.iconRight = 14
            style.fontSize = 14
            style.borderRadius = CocsoTokens.Radius.r4
        }
        return style
    }
}

public enum CCSkeletonVariant: String, CaseIterable, Sendable {
    case text
    case circular
    case rectangular
}

public enum CCSkeletonAnimation: String, CaseIterable, Sendable {
    case pulse
    case wave
    case none
}

public struct CCSkeletonStyle: Equatable, Sendable {
    public var bgColor: SwiftUI.Color?
    public var height: CGFloat?
    public var borderRadius: CGFloat?
    public var width: CGFloat?
    public var borderRadiusFull: Bool?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCSkeletonVariant,
        animation: CCSkeletonAnimation,
        scheme: ColorScheme
    ) -> CCSkeletonStyle {
        var style = CCSkeletonStyle()
        style.bgColor = CocsoTokens.Color.surfaceNeutral(scheme)
        if variant == .text {
            style.height = 16
            style.borderRadius = CocsoTokens.Radius.r2
        }
        if variant == .circular {
            style.height = 40
            style.width = 40
            style.borderRadiusFull = true
        }
        if variant == .rectangular {
            style.height = 120
            style.borderRadius = CocsoTokens.Radius.r4
        }
        return style
    }
}

public enum CCSpinnerVariant: String, CaseIterable, Sendable {
    case primary
    case secondary
    case success
    case error
    case warning
    case info
    case white
}

public enum CCSpinnerSize: String, CaseIterable, Sendable {
    case large
    case medium
    case small
}

public struct CCSpinnerStyle: Equatable, Sendable {
    public var bladeColor: SwiftUI.Color?
    public var blades: Int?
    public var bladeWidth: CGFloat?
    public var bladeHeight: CGFloat?
    public var bladeRadius: CGFloat?
    public var output: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCSpinnerVariant,
        size: CCSpinnerSize,
        scheme: ColorScheme
    ) -> CCSpinnerStyle {
        var style = CCSpinnerStyle()
        if variant == .primary {
            style.bladeColor = CocsoTokens.Color.interactivePrimary(scheme)
        }
        if variant == .secondary {
            style.bladeColor = CocsoTokens.Color.textMuted(scheme)
        }
        if variant == .success {
            style.bladeColor = CocsoTokens.Color.feedbackSuccess(scheme)
        }
        if variant == .error {
            style.bladeColor = CocsoTokens.Color.feedbackDanger(scheme)
        }
        if variant == .warning {
            style.bladeColor = CocsoTokens.Color.feedbackWarning(scheme)
        }
        if variant == .info {
            style.bladeColor = CocsoTokens.Color.feedbackInfo(scheme)
        }
        if variant == .white {
            style.bladeColor = CocsoTokens.Color.surfacePrimary(scheme)
        }
        if size == .large {
            style.blades = 10
            style.bladeWidth = 2
            style.bladeHeight = 6
            style.bladeRadius = 1
            style.output = 20
        }
        if size == .medium {
            style.blades = 8
            style.bladeWidth = 2
            style.bladeHeight = 5
            style.bladeRadius = 1
            style.output = 16
        }
        if size == .small {
            style.blades = 6
            style.bladeWidth = 1.5
            style.bladeHeight = 4
            style.bladeRadius = 0.75
            style.output = 12
        }
        return style
    }
}

public enum CCStockQuantityStatusQuantity: String, CaseIterable, Sendable {
    case sufficient
    case normal
    case insufficient
}

public struct CCStockQuantityStatusStyle: Equatable, Sendable {
    public var color: SwiftUI.Color?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        quantity: CCStockQuantityStatusQuantity,
        scheme: ColorScheme
    ) -> CCStockQuantityStatusStyle {
        var style = CCStockQuantityStatusStyle()
        if quantity == .sufficient {
            style.color = CocsoTokens.Color.feedbackInfoText(scheme)
        }
        if quantity == .normal {
            style.color = CocsoTokens.Color.feedbackSuccessText(scheme)
        }
        if quantity == .insufficient {
            style.color = CocsoTokens.Color.feedbackDangerText(scheme)
        }
        return style
    }
}

public enum CCSwitchVariant: String, CaseIterable, Sendable {
    case primary
    case success
    case error
    case warning
    case info
}

public enum CCSwitchSize: String, CaseIterable, Sendable {
    case large
    case medium
    case small
}

public enum CCSwitchChecked: String, CaseIterable, Sendable {
    case `true`
    case `false`
}

public struct CCSwitchStyle: Equatable, Sendable {
    public var switchBgColor: SwiftUI.Color?
    public var borderColor: SwiftUI.Color?
    public var checkedBgColor: SwiftUI.Color?
    public var width: CGFloat?
    public var height: CGFloat?
    public var thumbSize: CGFloat?
    public var thumbOffset: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        variant: CCSwitchVariant,
        size: CCSwitchSize,
        checked: CCSwitchChecked,
        scheme: ColorScheme
    ) -> CCSwitchStyle {
        var style = CCSwitchStyle()
        style.switchBgColor = CocsoTokens.Color.surfaceNeutral(scheme)
        style.borderColor = CocsoTokens.Color.borderStrong(scheme)
        if variant == .primary {
            style.checkedBgColor = CocsoTokens.Color.interactivePrimary(scheme)
        }
        if variant == .success {
            style.checkedBgColor = CocsoTokens.Color.interactiveSuccess(scheme)
        }
        if variant == .error {
            style.checkedBgColor = CocsoTokens.Color.interactiveDanger(scheme)
        }
        if variant == .warning {
            style.checkedBgColor = CocsoTokens.Color.interactiveWarningActive(scheme)
        }
        if variant == .info {
            style.checkedBgColor = CocsoTokens.Color.interactiveInfo(scheme)
        }
        if size == .large {
            style.width = 40
            style.height = 22
            style.thumbSize = 18
            style.thumbOffset = 2
        }
        if size == .medium {
            style.width = 36
            style.height = 20
            style.thumbSize = 16
            style.thumbOffset = 2
        }
        if size == .small {
            style.width = 32
            style.height = 18
            style.thumbSize = 14
            style.thumbOffset = 2
        }
        if variant == .primary && checked == .`true` {
            style.switchBgColor = CocsoTokens.Color.interactivePrimary(scheme)
        }
        if variant == .success && checked == .`true` {
            style.switchBgColor = CocsoTokens.Color.interactiveSuccess(scheme)
        }
        if variant == .error && checked == .`true` {
            style.switchBgColor = CocsoTokens.Color.interactiveDanger(scheme)
        }
        if variant == .warning && checked == .`true` {
            style.switchBgColor = CocsoTokens.Color.interactiveWarningActive(scheme)
        }
        if variant == .info && checked == .`true` {
            style.switchBgColor = CocsoTokens.Color.interactiveInfo(scheme)
        }
        return style
    }
}

public enum CCTypographyType: String, CaseIterable, Sendable {
    case body
    case heading
}

public enum CCTypographySize: String, CaseIterable, Sendable {
    case xLarge
    case large
    case medium
    case small
    case xSmall
}

public struct CCTypographyStyle: Equatable, Sendable {
    public var fontWeight: Font.Weight?
    public var fontSize: CGFloat?

    /// Base, then each variant dimension, then compound
    /// variants — the order the CSS cascade encodes.
    public static func resolve(
        type: CCTypographyType,
        size: CCTypographySize,
        scheme: ColorScheme
    ) -> CCTypographyStyle {
        var style = CCTypographyStyle()
        if type == .heading {
            style.fontWeight = .bold
        }
        if size == .xLarge {
            style.fontSize = 28
        }
        if size == .large {
            style.fontSize = 24
        }
        if size == .medium {
            style.fontSize = 20
        }
        if size == .small {
            style.fontSize = 16
        }
        if size == .xSmall {
            style.fontSize = 14
        }
        if type == .body && size == .xLarge {
            style.fontSize = 18
        }
        if type == .body && size == .large {
            style.fontSize = 18
        }
        if type == .body && size == .medium {
            style.fontSize = 16
        }
        if type == .body && size == .small {
            style.fontSize = 14
        }
        if type == .body && size == .xSmall {
            style.fontSize = 12
        }
        return style
    }
}
