// Generated by @cocso-ui/baseframe — do not edit.
// Source: packages/baseframe-sources
// Regenerate: pnpm --filter @cocso-ui/baseframe generate:mobile

import SwiftUI

private extension Color {
    init(hex: UInt32, opacity: Double = 1) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: opacity
        )
    }
}

public enum CocsoTokens {
    public enum Color {
        public static let black: SwiftUI.Color = SwiftUI.Color(hex: 0x000000)
        public static let blackAlpha10: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.1)
        public static let blackAlpha20: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.2)
        public static let blackAlpha30: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.3)
        public static let blackAlpha40: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.4)
        public static let blackAlpha5: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.05)
        public static let blackAlpha50: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.5)
        public static let blackAlpha60: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.6)
        public static let blackAlpha70: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.7)
        public static let blackAlpha80: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.8)
        public static let blackAlpha90: SwiftUI.Color = SwiftUI.Color(hex: 0x000000, opacity: 0.9)
        public static let danger100: SwiftUI.Color = SwiftUI.Color(hex: 0xFCDFD9)
        public static let danger200: SwiftUI.Color = SwiftUI.Color(hex: 0xF7AFA1)
        public static let danger300: SwiftUI.Color = SwiftUI.Color(hex: 0xF48771)
        public static let danger400: SwiftUI.Color = SwiftUI.Color(hex: 0xF05F42)
        public static let danger50: SwiftUI.Color = SwiftUI.Color(hex: 0xFDEFEC)
        public static let danger500: SwiftUI.Color = SwiftUI.Color(hex: 0xDE3412)
        public static let danger600: SwiftUI.Color = SwiftUI.Color(hex: 0xBD2C0F)
        public static let danger700: SwiftUI.Color = SwiftUI.Color(hex: 0x8A240F)
        public static let danger800: SwiftUI.Color = SwiftUI.Color(hex: 0x5C180A)
        public static let danger900: SwiftUI.Color = SwiftUI.Color(hex: 0x390D05)
        public static let danger950: SwiftUI.Color = SwiftUI.Color(hex: 0x260903)
        public static let info100: SwiftUI.Color = SwiftUI.Color(hex: 0xD8E5FD)
        public static let info200: SwiftUI.Color = SwiftUI.Color(hex: 0xB1CEFB)
        public static let info300: SwiftUI.Color = SwiftUI.Color(hex: 0x86AFF9)
        public static let info400: SwiftUI.Color = SwiftUI.Color(hex: 0x4C87F6)
        public static let info50: SwiftUI.Color = SwiftUI.Color(hex: 0xECF2FE)
        public static let info500: SwiftUI.Color = SwiftUI.Color(hex: 0x256EF4)
        public static let info600: SwiftUI.Color = SwiftUI.Color(hex: 0x0B50D0)
        public static let info700: SwiftUI.Color = SwiftUI.Color(hex: 0x083891)
        public static let info800: SwiftUI.Color = SwiftUI.Color(hex: 0x052561)
        public static let info900: SwiftUI.Color = SwiftUI.Color(hex: 0x03163A)
        public static let info950: SwiftUI.Color = SwiftUI.Color(hex: 0x020F27)
        public static let neutral100: SwiftUI.Color = SwiftUI.Color(hex: 0xE6E8EA)
        public static let neutral200: SwiftUI.Color = SwiftUI.Color(hex: 0xCDD1D5)
        public static let neutral300: SwiftUI.Color = SwiftUI.Color(hex: 0xB1B8BE)
        public static let neutral400: SwiftUI.Color = SwiftUI.Color(hex: 0x8A949E)
        public static let neutral50: SwiftUI.Color = SwiftUI.Color(hex: 0xF4F5F6)
        public static let neutral500: SwiftUI.Color = SwiftUI.Color(hex: 0x6D7882)
        public static let neutral600: SwiftUI.Color = SwiftUI.Color(hex: 0x58616A)
        public static let neutral700: SwiftUI.Color = SwiftUI.Color(hex: 0x464C53)
        public static let neutral800: SwiftUI.Color = SwiftUI.Color(hex: 0x33363D)
        public static let neutral900: SwiftUI.Color = SwiftUI.Color(hex: 0x1E2124)
        public static let neutral950: SwiftUI.Color = SwiftUI.Color(hex: 0x131416)
        public static let primary100: SwiftUI.Color = SwiftUI.Color(hex: 0xE6E8EA)
        public static let primary200: SwiftUI.Color = SwiftUI.Color(hex: 0xCDD1D5)
        public static let primary300: SwiftUI.Color = SwiftUI.Color(hex: 0xB1B8BE)
        public static let primary400: SwiftUI.Color = SwiftUI.Color(hex: 0x8A949E)
        public static let primary50: SwiftUI.Color = SwiftUI.Color(hex: 0xF4F5F6)
        public static let primary500: SwiftUI.Color = SwiftUI.Color(hex: 0x6D7882)
        public static let primary600: SwiftUI.Color = SwiftUI.Color(hex: 0x58616A)
        public static let primary700: SwiftUI.Color = SwiftUI.Color(hex: 0x464C53)
        public static let primary800: SwiftUI.Color = SwiftUI.Color(hex: 0x33363D)
        public static let primary900: SwiftUI.Color = SwiftUI.Color(hex: 0x1E2124)
        public static let primary950: SwiftUI.Color = SwiftUI.Color(hex: 0x131416)
        public static let success100: SwiftUI.Color = SwiftUI.Color(hex: 0xD8EEDD)
        public static let success200: SwiftUI.Color = SwiftUI.Color(hex: 0xA9DAB4)
        public static let success300: SwiftUI.Color = SwiftUI.Color(hex: 0x7EC88E)
        public static let success400: SwiftUI.Color = SwiftUI.Color(hex: 0x3FA654)
        public static let success50: SwiftUI.Color = SwiftUI.Color(hex: 0xEAF6EC)
        public static let success500: SwiftUI.Color = SwiftUI.Color(hex: 0x228738)
        public static let success600: SwiftUI.Color = SwiftUI.Color(hex: 0x267337)
        public static let success700: SwiftUI.Color = SwiftUI.Color(hex: 0x285D33)
        public static let success800: SwiftUI.Color = SwiftUI.Color(hex: 0x1F4727)
        public static let success900: SwiftUI.Color = SwiftUI.Color(hex: 0x122B18)
        public static let success950: SwiftUI.Color = SwiftUI.Color(hex: 0x0E2012)
        public static let warning100: SwiftUI.Color = SwiftUI.Color(hex: 0xFFE0A3)
        public static let warning200: SwiftUI.Color = SwiftUI.Color(hex: 0xFFC95C)
        public static let warning300: SwiftUI.Color = SwiftUI.Color(hex: 0xFFB114)
        public static let warning400: SwiftUI.Color = SwiftUI.Color(hex: 0xC78500)
        public static let warning50: SwiftUI.Color = SwiftUI.Color(hex: 0xFFF3DB)
        public static let warning500: SwiftUI.Color = SwiftUI.Color(hex: 0x9E6A00)
        public static let warning600: SwiftUI.Color = SwiftUI.Color(hex: 0x8A5C00)
        public static let warning700: SwiftUI.Color = SwiftUI.Color(hex: 0x614100)
        public static let warning800: SwiftUI.Color = SwiftUI.Color(hex: 0x422C00)
        public static let warning900: SwiftUI.Color = SwiftUI.Color(hex: 0x2E1F00)
        public static let warning950: SwiftUI.Color = SwiftUI.Color(hex: 0x241800)
        public static let white: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF)
        public static let whiteAlpha10: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.1)
        public static let whiteAlpha20: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.2)
        public static let whiteAlpha30: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.3)
        public static let whiteAlpha40: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.4)
        public static let whiteAlpha5: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.05)
        public static let whiteAlpha50: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.5)
        public static let whiteAlpha60: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.6)
        public static let whiteAlpha70: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.7)
        public static let whiteAlpha80: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.8)
        public static let whiteAlpha90: SwiftUI.Color = SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.9)

        /// Resolved against the view's colour scheme. Read these as
        /// `CocsoTokens.Color.textPrimary(scheme)`, with `scheme` from
        /// `@Environment(\.colorScheme)`.
        public static func alphaShadow1(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x000000, opacity: 0.24) : SwiftUI.Color(hex: 0x000000, opacity: 0.04)
        }
        public static func alphaShadow2(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x000000, opacity: 0.36) : SwiftUI.Color(hex: 0x000000, opacity: 0.08)
        }
        public static func alphaShadow3(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x000000, opacity: 0.48) : SwiftUI.Color(hex: 0x000000, opacity: 0.12)
        }
        public static func borderPrimary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x464C53) : SwiftUI.Color(hex: 0xCDD1D5)
        }
        public static func borderSecondary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x33363D) : SwiftUI.Color(hex: 0xE6E8EA)
        }
        public static func borderStrong(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x6D7882) : SwiftUI.Color(hex: 0x8A949E)
        }
        public static func feedbackDanger(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xF05F42) : SwiftUI.Color(hex: 0xDE3412)
        }
        public static func feedbackDangerBorder(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x5C180A) : SwiftUI.Color(hex: 0xF7AFA1)
        }
        public static func feedbackDangerSubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x260903) : SwiftUI.Color(hex: 0xFDEFEC)
        }
        public static func feedbackDangerText(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xF48771) : SwiftUI.Color(hex: 0xBD2C0F)
        }
        public static func feedbackInfo(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x4C87F6) : SwiftUI.Color(hex: 0x256EF4)
        }
        public static func feedbackInfoBorder(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x052561) : SwiftUI.Color(hex: 0xB1CEFB)
        }
        public static func feedbackInfoSubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x020F27) : SwiftUI.Color(hex: 0xECF2FE)
        }
        public static func feedbackInfoText(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x86AFF9) : SwiftUI.Color(hex: 0x0B50D0)
        }
        public static func feedbackSuccess(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x3FA654) : SwiftUI.Color(hex: 0x228738)
        }
        public static func feedbackSuccessBorder(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x1F4727) : SwiftUI.Color(hex: 0xA9DAB4)
        }
        public static func feedbackSuccessMuted(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x3FA654) : SwiftUI.Color(hex: 0x3FA654)
        }
        public static func feedbackSuccessSubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x0E2012) : SwiftUI.Color(hex: 0xEAF6EC)
        }
        public static func feedbackSuccessText(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x7EC88E) : SwiftUI.Color(hex: 0x267337)
        }
        public static func feedbackWarning(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xC78500) : SwiftUI.Color(hex: 0x9E6A00)
        }
        public static func feedbackWarningBorder(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x422C00) : SwiftUI.Color(hex: 0xFFC95C)
        }
        public static func feedbackWarningSubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x241800) : SwiftUI.Color(hex: 0xFFF3DB)
        }
        public static func feedbackWarningText(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFB114) : SwiftUI.Color(hex: 0x8A5C00)
        }
        public static func focusRing(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xF4F5F6) : SwiftUI.Color(hex: 0x131416)
        }
        public static func interactiveDanger(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xDE3412) : SwiftUI.Color(hex: 0xDE3412)
        }
        public static func interactiveDangerActive(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x8A240F) : SwiftUI.Color(hex: 0x8A240F)
        }
        public static func interactiveDangerHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xBD2C0F) : SwiftUI.Color(hex: 0xBD2C0F)
        }
        public static func interactiveDangerHoverSubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xF05F42) : SwiftUI.Color(hex: 0xF05F42)
        }
        public static func interactiveDangerSubtleActive(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x390D05) : SwiftUI.Color(hex: 0xFCDFD9)
        }
        public static func interactiveDangerSubtleHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x260903) : SwiftUI.Color(hex: 0xFDEFEC)
        }
        public static func interactiveInfo(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x256EF4) : SwiftUI.Color(hex: 0x256EF4)
        }
        public static func interactiveInfoActive(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x083891) : SwiftUI.Color(hex: 0x083891)
        }
        public static func interactiveInfoHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x0B50D0) : SwiftUI.Color(hex: 0x0B50D0)
        }
        public static func interactiveInfoHoverSubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x4C87F6) : SwiftUI.Color(hex: 0x4C87F6)
        }
        public static func interactiveInfoText(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x86AFF9) : SwiftUI.Color(hex: 0x0B50D0)
        }
        public static func interactiveInfoTextHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xB1CEFB) : SwiftUI.Color(hex: 0x083891)
        }
        public static func interactiveNeutral(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x33363D) : SwiftUI.Color(hex: 0xE6E8EA)
        }
        public static func interactiveNeutralActive(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x58616A) : SwiftUI.Color(hex: 0xB1B8BE)
        }
        public static func interactiveNeutralHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x464C53) : SwiftUI.Color(hex: 0xCDD1D5)
        }
        public static func interactivePrimary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xF4F5F6) : SwiftUI.Color(hex: 0x131416)
        }
        public static func interactivePrimaryActive(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xB1B8BE) : SwiftUI.Color(hex: 0x464C53)
        }
        public static func interactivePrimaryHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xCDD1D5) : SwiftUI.Color(hex: 0x33363D)
        }
        public static func interactivePrimaryMuted(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x6D7882) : SwiftUI.Color(hex: 0x6D7882)
        }
        public static func interactivePrimarySubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x1E2124) : SwiftUI.Color(hex: 0xE6E8EA)
        }
        public static func interactivePrimaryText(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xCDD1D5) : SwiftUI.Color(hex: 0x33363D)
        }
        public static func interactiveSecondary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x33363D) : SwiftUI.Color(hex: 0xE6E8EA)
        }
        public static func interactiveSecondaryHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x464C53) : SwiftUI.Color(hex: 0xCDD1D5)
        }
        public static func interactiveSuccess(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x228738) : SwiftUI.Color(hex: 0x228738)
        }
        public static func interactiveSuccessActive(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x285D33) : SwiftUI.Color(hex: 0x285D33)
        }
        public static func interactiveSuccessHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x267337) : SwiftUI.Color(hex: 0x267337)
        }
        public static func interactiveSuccessHoverSubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x3FA654) : SwiftUI.Color(hex: 0x3FA654)
        }
        public static func interactiveWarning(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFB114) : SwiftUI.Color(hex: 0xFFB114)
        }
        public static func interactiveWarningActive(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x9E6A00) : SwiftUI.Color(hex: 0x9E6A00)
        }
        public static func interactiveWarningHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xC78500) : SwiftUI.Color(hex: 0xC78500)
        }
        public static func interactiveWarningHoverSubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xC78500) : SwiftUI.Color(hex: 0xC78500)
        }
        public static func overlayMuted(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.1) : SwiftUI.Color(hex: 0x000000, opacity: 0.1)
        }
        public static func overlayStrong(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.2) : SwiftUI.Color(hex: 0x000000, opacity: 0.2)
        }
        public static func overlaySubtle(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFFFFF, opacity: 0.05) : SwiftUI.Color(hex: 0x000000, opacity: 0.05)
        }
        public static func surfaceInverse(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFFFFF) : SwiftUI.Color(hex: 0x131416)
        }
        public static func surfaceNeutral(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x33363D) : SwiftUI.Color(hex: 0xE6E8EA)
        }
        public static func surfacePrimary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x131416) : SwiftUI.Color(hex: 0xFFFFFF)
        }
        public static func surfaceSecondary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x1E2124) : SwiftUI.Color(hex: 0xF4F5F6)
        }
        public static func textDisabled(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x58616A) : SwiftUI.Color(hex: 0x8A949E)
        }
        public static func textMuted(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x6D7882) : SwiftUI.Color(hex: 0x6D7882)
        }
        public static func textOnDanger(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFFFFF) : SwiftUI.Color(hex: 0xFFFFFF)
        }
        public static func textOnInfo(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFFFFF) : SwiftUI.Color(hex: 0xFFFFFF)
        }
        public static func textOnPrimary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x131416) : SwiftUI.Color(hex: 0xFFFFFF)
        }
        public static func textOnSuccess(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFFFFF) : SwiftUI.Color(hex: 0xFFFFFF)
        }
        public static func textOnWarning(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x131416) : SwiftUI.Color(hex: 0x131416)
        }
        public static func textPrimary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xF4F5F6) : SwiftUI.Color(hex: 0x131416)
        }
        public static func textSecondary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x8A949E) : SwiftUI.Color(hex: 0x58616A)
        }
        public static func textTertiary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x6D7882) : SwiftUI.Color(hex: 0x8A949E)
        }
    }

    public enum Text {
        public static let base: CGFloat = 16
        public static let sm: CGFloat = 14
        public static let xs: CGFloat = 12
    }

    public enum FontWeight {
        public static let black: CGFloat = 900
        public static let bold: CGFloat = 700
        public static let extrabold: CGFloat = 800
        public static let extralight: CGFloat = 200
        public static let light: CGFloat = 300
        public static let medium: CGFloat = 500
        public static let regular: CGFloat = 400
        public static let semibold: CGFloat = 600
        public static let thin: CGFloat = 100
    }

    public enum Radius {
        public static let full: CGFloat = 1000
        public static let r1: CGFloat = 2
        public static let r2: CGFloat = 4
        public static let r3: CGFloat = 6
        public static let r4: CGFloat = 8
        public static let r5: CGFloat = 12
        public static let r6: CGFloat = 16
    }

    public enum Shadow {
        public static let blur3: CGFloat = 16
        public static let blur4: CGFloat = 24
        public static let y3: CGFloat = 8
        public static let y4: CGFloat = 16
    }

    public enum Spacing {
        public static let max: CGFloat = 1000
        public static let s0: CGFloat = 0
        public static let s1: CGFloat = 1
        public static let s10: CGFloat = 24
        public static let s11: CGFloat = 28
        public static let s12: CGFloat = 32
        public static let s13: CGFloat = 36
        public static let s14: CGFloat = 40
        public static let s15: CGFloat = 44
        public static let s16: CGFloat = 48
        public static let s17: CGFloat = 56
        public static let s18: CGFloat = 64
        public static let s19: CGFloat = 72
        public static let s2: CGFloat = 2
        public static let s20: CGFloat = 80
        public static let s21: CGFloat = 96
        public static let s3: CGFloat = 4
        public static let s4: CGFloat = 6
        public static let s5: CGFloat = 8
        public static let s6: CGFloat = 10
        public static let s7: CGFloat = 12
        public static let s8: CGFloat = 16
        public static let s9: CGFloat = 20
    }

    public enum ZIndex {
        public static let above: CGFloat = 1
        public static let base: CGFloat = 0
        public static let behind: CGFloat = -1
        public static let dialog: CGFloat = 200
        public static let dialogContent: CGFloat = 250
        public static let header: CGFloat = 50
        public static let overlay: CGFloat = 100
        public static let popover: CGFloat = 300
        public static let tooltip: CGFloat = 400
    }

    public enum Duration {
        public static let decorative: CGFloat = 0.75
        public static let decorativeSlow: CGFloat = 1.5
        public static let fast: CGFloat = 0.15
        public static let normal: CGFloat = 0.2
        public static let slow: CGFloat = 0.25
    }

}
