// Generated by @cocso-ui/baseframe — do not edit.
// Source: packages/baseframe-sources
// Regenerate: pnpm --filter @cocso-ui/baseframe generate:mobile

import SwiftUI

private extension Color {
    init(hex: UInt32, opacity: Double = 1) {
        self.init(
            .sRGB,
            red: Double((hex >> 16) & 0xFF) / 255,
            green: Double((hex >> 8) & 0xFF) / 255,
            blue: Double(hex & 0xFF) / 255,
            opacity: opacity
        )
    }
}

public enum CocsoBrandCocso {
    public enum Color {

        /// Resolved against the view's colour scheme. Read these as
        /// `CocsoTokens.Color.textPrimary(scheme)`, with `scheme` from
        /// `@Environment(\.colorScheme)`.
        public static func interactivePrimary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x2260D3) : SwiftUI.Color(hex: 0x256EF4)
        }
        public static func interactivePrimaryActive(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x083891) : SwiftUI.Color(hex: 0x083891)
        }
        public static func interactivePrimaryHover(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x0B50D0) : SwiftUI.Color(hex: 0x0B50D0)
        }
        public static func interactivePrimaryMuted(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x256EF4) : SwiftUI.Color(hex: 0x256EF4)
        }
        public static func primary100(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xD8E5FD) : SwiftUI.Color(hex: 0xD8E5FD)
        }
        public static func primary200(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xB1CEFB) : SwiftUI.Color(hex: 0xB1CEFB)
        }
        public static func primary300(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x86AFF9) : SwiftUI.Color(hex: 0x86AFF9)
        }
        public static func primary400(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x4C87F6) : SwiftUI.Color(hex: 0x4C87F6)
        }
        public static func primary50(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xECF2FE) : SwiftUI.Color(hex: 0xECF2FE)
        }
        public static func primary500(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x256EF4) : SwiftUI.Color(hex: 0x256EF4)
        }
        public static func primary600(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x0B50D0) : SwiftUI.Color(hex: 0x0B50D0)
        }
        public static func primary700(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x083891) : SwiftUI.Color(hex: 0x083891)
        }
        public static func primary800(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x052561) : SwiftUI.Color(hex: 0x052561)
        }
        public static func primary900(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x03163A) : SwiftUI.Color(hex: 0x03163A)
        }
        public static func primary950(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0x020F27) : SwiftUI.Color(hex: 0x020F27)
        }
        public static func textOnPrimary(_ scheme: ColorScheme) -> SwiftUI.Color {
            scheme == .dark ? SwiftUI.Color(hex: 0xFFFFFF) : SwiftUI.Color(hex: 0xFFFFFF)
        }
    }

}
