// Generated by @cocso-ui/codegen — do not edit.
// Source: packages/recipe/src/recipes
// Regenerate: pnpm --filter @cocso-ui/codegen generate:mobile

package ai.cocso.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.Color as ComposeColor
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

enum class CCAlertVariant {
    info,
    success,
    warning,
    error,
}

data class CCAlertStyle(
    val borderRadius: Dp? = null,
    val paddingX: Dp? = null,
    val paddingY: Dp? = null,
    val fontSize: Dp? = null,
    val bgColor: ComposeColor? = null,
    val fontColor: ComposeColor? = null,
    val borderColor: ComposeColor? = null,
)

@Composable
@ReadOnlyComposable
fun cCAlertStyle(
    variant: CCAlertVariant,
): CCAlertStyle {
    var style = CCAlertStyle()
    style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    style = style.copy(paddingX = 16.dp)
    style = style.copy(paddingY = 12.dp)
    style = style.copy(fontSize = 14.dp)
    if (variant == CCAlertVariant.info) {
        style = style.copy(bgColor = CocsoTokens.Color.feedbackInfoSubtle())
        style = style.copy(fontColor = CocsoTokens.Color.feedbackInfoText())
        style = style.copy(borderColor = CocsoTokens.Color.feedbackInfoBorder())
    }
    if (variant == CCAlertVariant.success) {
        style = style.copy(bgColor = CocsoTokens.Color.feedbackSuccessSubtle())
        style = style.copy(fontColor = CocsoTokens.Color.feedbackSuccessText())
        style = style.copy(borderColor = CocsoTokens.Color.feedbackSuccessBorder())
    }
    if (variant == CCAlertVariant.warning) {
        style = style.copy(bgColor = CocsoTokens.Color.feedbackWarningSubtle())
        style = style.copy(fontColor = CocsoTokens.Color.feedbackWarningText())
        style = style.copy(borderColor = CocsoTokens.Color.feedbackWarningBorder())
    }
    if (variant == CCAlertVariant.error) {
        style = style.copy(bgColor = CocsoTokens.Color.feedbackDangerSubtle())
        style = style.copy(fontColor = CocsoTokens.Color.feedbackDangerText())
        style = style.copy(borderColor = CocsoTokens.Color.feedbackDangerBorder())
    }
    return style
}

enum class CCAvatarSize {
    xs,
    sm,
    md,
    lg,
    xl,
}

enum class CCAvatarShape {
    circle,
    square,
}

data class CCAvatarStyle(
    val bgColor: ComposeColor? = null,
    val fontColor: ComposeColor? = null,
    val fontWeight: FontWeight? = null,
    val height: Dp? = null,
    val width: Dp? = null,
    val fontSize: Dp? = null,
    val borderRadius: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCAvatarStyle(
    size: CCAvatarSize,
    shape: CCAvatarShape,
): CCAvatarStyle {
    var style = CCAvatarStyle()
    style = style.copy(bgColor = CocsoTokens.Color.surfaceNeutral())
    style = style.copy(fontColor = CocsoTokens.Color.textPrimary())
    style = style.copy(fontWeight = FontWeight.Medium)
    if (size == CCAvatarSize.xs) {
        style = style.copy(height = 24.dp)
        style = style.copy(width = 24.dp)
        style = style.copy(fontSize = 10.dp)
    }
    if (size == CCAvatarSize.sm) {
        style = style.copy(height = 32.dp)
        style = style.copy(width = 32.dp)
        style = style.copy(fontSize = 12.dp)
    }
    if (size == CCAvatarSize.md) {
        style = style.copy(height = 40.dp)
        style = style.copy(width = 40.dp)
        style = style.copy(fontSize = 14.dp)
    }
    if (size == CCAvatarSize.lg) {
        style = style.copy(height = 48.dp)
        style = style.copy(width = 48.dp)
        style = style.copy(fontSize = 16.dp)
    }
    if (size == CCAvatarSize.xl) {
        style = style.copy(height = 64.dp)
        style = style.copy(width = 64.dp)
        style = style.copy(fontSize = 20.dp)
    }
    if (shape == CCAvatarShape.square && size == CCAvatarSize.xs) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r2)
    }
    if (shape == CCAvatarShape.square && size == CCAvatarSize.sm) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r3)
    }
    if (shape == CCAvatarShape.square && size == CCAvatarSize.md) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (shape == CCAvatarShape.square && size == CCAvatarSize.lg) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (shape == CCAvatarShape.square && size == CCAvatarSize.xl) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r5)
    }
    return style
}

enum class CCBadgeVariant {
    primary,
    primarySubtle,
    secondary,
    success,
    error,
    warning,
    info,
    outline,
}

enum class CCBadgeSize {
    large,
    medium,
    small,
}

enum class CCBadgeShape {
    square,
    circle,
    rounded,
}

data class CCBadgeStyle(
    val bgColor: ComposeColor? = null,
    val fontColor: ComposeColor? = null,
    val paddingX: Dp? = null,
    val paddingY: Dp? = null,
    val fontSize: Dp? = null,
    val borderRadius: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCBadgeStyle(
    variant: CCBadgeVariant,
    size: CCBadgeSize,
    shape: CCBadgeShape,
): CCBadgeStyle {
    var style = CCBadgeStyle()
    if (variant == CCBadgeVariant.primary) {
        style = style.copy(bgColor = CocsoTokens.Color.interactivePrimary())
        style = style.copy(fontColor = CocsoTokens.Color.textOnPrimary())
    }
    if (variant == CCBadgeVariant.primarySubtle) {
        style = style.copy(bgColor = CocsoTokens.Color.interactivePrimarySubtle())
        style = style.copy(fontColor = CocsoTokens.Color.interactivePrimaryText())
    }
    if (variant == CCBadgeVariant.secondary) {
        style = style.copy(bgColor = CocsoTokens.Color.surfaceSecondary())
        style = style.copy(fontColor = CocsoTokens.Color.textSecondary())
    }
    if (variant == CCBadgeVariant.success) {
        style = style.copy(bgColor = CocsoTokens.Color.feedbackSuccessSubtle())
        style = style.copy(fontColor = CocsoTokens.Color.feedbackSuccessText())
    }
    if (variant == CCBadgeVariant.error) {
        style = style.copy(bgColor = CocsoTokens.Color.feedbackDangerSubtle())
        style = style.copy(fontColor = CocsoTokens.Color.feedbackDangerText())
    }
    if (variant == CCBadgeVariant.warning) {
        style = style.copy(bgColor = CocsoTokens.Color.feedbackWarningSubtle())
        style = style.copy(fontColor = CocsoTokens.Color.feedbackWarningText())
    }
    if (variant == CCBadgeVariant.info) {
        style = style.copy(bgColor = CocsoTokens.Color.feedbackInfoSubtle())
        style = style.copy(fontColor = CocsoTokens.Color.feedbackInfoText())
    }
    if (variant == CCBadgeVariant.outline) {
        style = style.copy(fontColor = CocsoTokens.Color.textPrimary())
    }
    if (size == CCBadgeSize.large) {
        style = style.copy(paddingX = 10.dp)
        style = style.copy(paddingY = 5.dp)
        style = style.copy(fontSize = 14.dp)
    }
    if (size == CCBadgeSize.medium) {
        style = style.copy(paddingX = 8.dp)
        style = style.copy(paddingY = 4.dp)
        style = style.copy(fontSize = 12.dp)
    }
    if (size == CCBadgeSize.small) {
        style = style.copy(paddingX = 6.dp)
        style = style.copy(paddingY = 3.dp)
        style = style.copy(fontSize = 11.dp)
    }
    if (shape == CCBadgeShape.rounded) {
        style = style.copy(borderRadius = CocsoTokens.Radius.full)
    }
    if (shape == CCBadgeShape.square && size == CCBadgeSize.small) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r3)
    }
    if (shape == CCBadgeShape.square && size == CCBadgeSize.large) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (shape == CCBadgeShape.square && size == CCBadgeSize.medium) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    return style
}

enum class CCBreadcrumbSize {
    sm,
    md,
    lg,
}

data class CCBreadcrumbStyle(
    val fontColor: ComposeColor? = null,
    val fontSize: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCBreadcrumbStyle(
    size: CCBreadcrumbSize,
): CCBreadcrumbStyle {
    var style = CCBreadcrumbStyle()
    style = style.copy(fontColor = CocsoTokens.Color.textSecondary())
    if (size == CCBreadcrumbSize.sm) {
        style = style.copy(fontSize = 12.dp)
    }
    if (size == CCBreadcrumbSize.md) {
        style = style.copy(fontSize = 14.dp)
    }
    if (size == CCBreadcrumbSize.lg) {
        style = style.copy(fontSize = 16.dp)
    }
    return style
}

enum class CCButtonVariant {
    primary,
    secondary,
    outline,
    ghost,
    success,
    error,
    warning,
    info,
    neutral,
    errorGhost,
}

enum class CCButtonSize {
    large,
    medium,
    small,
    xSmall,
}

enum class CCButtonShape {
    square,
    circle,
    rounded,
    sharp,
}

enum class CCButtonAlign {
    center,
    start,
    between,
}

data class CCButtonStyle(
    val bgColor: ComposeColor? = null,
    val fontColor: ComposeColor? = null,
    val height: Dp? = null,
    val paddingInline: Dp? = null,
    val fontSize: Dp? = null,
    val borderRadius: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCButtonStyle(
    variant: CCButtonVariant,
    size: CCButtonSize,
    shape: CCButtonShape,
    align: CCButtonAlign,
): CCButtonStyle {
    var style = CCButtonStyle()
    if (variant == CCButtonVariant.primary) {
        style = style.copy(bgColor = CocsoTokens.Color.interactivePrimary())
        style = style.copy(fontColor = CocsoTokens.Color.textOnPrimary())
    }
    if (variant == CCButtonVariant.secondary) {
        style = style.copy(bgColor = CocsoTokens.Color.surfaceSecondary())
        style = style.copy(fontColor = CocsoTokens.Color.textSecondary())
    }
    if (variant == CCButtonVariant.outline) {
        style = style.copy(fontColor = CocsoTokens.Color.textPrimary())
    }
    if (variant == CCButtonVariant.ghost) {
        style = style.copy(bgColor = CocsoTokens.Color.surfacePrimary())
        style = style.copy(fontColor = CocsoTokens.Color.textPrimary())
    }
    if (variant == CCButtonVariant.success) {
        style = style.copy(bgColor = CocsoTokens.Color.interactiveSuccess())
        style = style.copy(fontColor = CocsoTokens.Color.textOnSuccess())
    }
    if (variant == CCButtonVariant.error) {
        style = style.copy(bgColor = CocsoTokens.Color.interactiveDanger())
        style = style.copy(fontColor = CocsoTokens.Color.textOnDanger())
    }
    if (variant == CCButtonVariant.warning) {
        style = style.copy(bgColor = CocsoTokens.Color.interactiveWarning())
        style = style.copy(fontColor = CocsoTokens.Color.textOnWarning())
    }
    if (variant == CCButtonVariant.info) {
        style = style.copy(bgColor = CocsoTokens.Color.interactiveInfo())
        style = style.copy(fontColor = CocsoTokens.Color.textOnInfo())
    }
    if (variant == CCButtonVariant.neutral) {
        style = style.copy(bgColor = CocsoTokens.Color.interactiveNeutral())
        style = style.copy(fontColor = CocsoTokens.Color.textPrimary())
    }
    if (variant == CCButtonVariant.errorGhost) {
        style = style.copy(fontColor = CocsoTokens.Color.feedbackDangerText())
    }
    if (size == CCButtonSize.large) {
        style = style.copy(height = 40.dp)
        style = style.copy(paddingInline = 14.dp)
        style = style.copy(fontSize = 14.dp)
    }
    if (size == CCButtonSize.medium) {
        style = style.copy(height = 36.dp)
        style = style.copy(paddingInline = 12.dp)
        style = style.copy(fontSize = 14.dp)
    }
    if (size == CCButtonSize.small) {
        style = style.copy(height = 32.dp)
        style = style.copy(paddingInline = 10.dp)
        style = style.copy(fontSize = 14.dp)
    }
    if (size == CCButtonSize.xSmall) {
        style = style.copy(height = 28.dp)
        style = style.copy(paddingInline = 8.dp)
        style = style.copy(fontSize = 12.dp)
    }
    if (shape == CCButtonShape.rounded) {
        style = style.copy(borderRadius = CocsoTokens.Radius.full)
    }
    if (shape == CCButtonShape.square && size == CCButtonSize.xSmall) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r3)
    }
    if (shape == CCButtonShape.square && size == CCButtonSize.large) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (shape == CCButtonShape.square && size == CCButtonSize.medium) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (shape == CCButtonShape.square && size == CCButtonSize.small) {
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    return style
}

enum class CCCardVariant {
    elevated,
    outlined,
    filled,
}

enum class CCCardPadding {
    sm,
    md,
    lg,
}

data class CCCardStyle(
    val bgColor: ComposeColor? = null,
    val borderRadius: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCCardStyle(
    variant: CCCardVariant,
    padding: CCCardPadding,
): CCCardStyle {
    var style = CCCardStyle()
    if (variant == CCCardVariant.elevated) {
        style = style.copy(bgColor = CocsoTokens.Color.surfacePrimary())
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (variant == CCCardVariant.outlined) {
        style = style.copy(bgColor = CocsoTokens.Color.surfacePrimary())
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (variant == CCCardVariant.filled) {
        style = style.copy(bgColor = CocsoTokens.Color.surfaceSecondary())
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    return style
}

enum class CCCheckboxSize {
    large,
    medium,
    small,
}

enum class CCCheckboxStatus {
    on,
    off,
    intermediate,
}

data class CCCheckboxStyle(
    val focusRingColor: ComposeColor? = null,
    val size: Dp? = null,
    val radius: Dp? = null,
    val borderColor: ComposeColor? = null,
    val bgColor: ComposeColor? = null,
)

@Composable
@ReadOnlyComposable
fun cCCheckboxStyle(
    size: CCCheckboxSize,
    status: CCCheckboxStatus,
): CCCheckboxStyle {
    var style = CCCheckboxStyle()
    style = style.copy(focusRingColor = CocsoTokens.Color.focusRing())
    if (size == CCCheckboxSize.large) {
        style = style.copy(size = 18.dp)
        style = style.copy(radius = CocsoTokens.Radius.r3)
    }
    if (size == CCCheckboxSize.medium) {
        style = style.copy(size = 16.dp)
        style = style.copy(radius = CocsoTokens.Radius.r2)
    }
    if (size == CCCheckboxSize.small) {
        style = style.copy(size = 14.dp)
        style = style.copy(radius = CocsoTokens.Radius.r1)
    }
    if (status == CCCheckboxStatus.on) {
        style = style.copy(borderColor = CocsoTokens.Color.interactivePrimary())
        style = style.copy(bgColor = CocsoTokens.Color.interactivePrimary())
    }
    if (status == CCCheckboxStatus.off) {
        style = style.copy(borderColor = CocsoTokens.Color.borderSecondary())
        style = style.copy(bgColor = CocsoTokens.Color.surfacePrimary())
    }
    if (status == CCCheckboxStatus.intermediate) {
        style = style.copy(borderColor = CocsoTokens.Color.interactivePrimary())
        style = style.copy(bgColor = CocsoTokens.Color.interactivePrimary())
    }
    return style
}

enum class CCDialogSize {
    small,
    medium,
    large,
}

data class CCDialogStyle(
    val bgColor: ComposeColor? = null,
    val borderRadius: Dp? = null,
    val paddingTop: Dp? = null,
    val paddingBottom: Dp? = null,
    val paddingLeft: Dp? = null,
    val paddingRight: Dp? = null,
    val width: Dp? = null,
    val height: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCDialogStyle(
    size: CCDialogSize,
): CCDialogStyle {
    var style = CCDialogStyle()
    style = style.copy(bgColor = CocsoTokens.Color.surfacePrimary())
    style = style.copy(borderRadius = CocsoTokens.Radius.r5)
    style = style.copy(paddingTop = 20.dp)
    style = style.copy(paddingBottom = 20.dp)
    style = style.copy(paddingLeft = 20.dp)
    style = style.copy(paddingRight = 20.dp)
    if (size == CCDialogSize.small) {
        style = style.copy(width = 380.dp)
        style = style.copy(height = 200.dp)
    }
    if (size == CCDialogSize.medium) {
        style = style.copy(width = 520.dp)
        style = style.copy(height = 260.dp)
    }
    if (size == CCDialogSize.large) {
        style = style.copy(width = 680.dp)
        style = style.copy(height = 340.dp)
    }
    return style
}

enum class CCInputSize {
    xSmall,
    small,
    medium,
    large,
}

data class CCInputStyle(
    val borderColor: ComposeColor? = null,
    val height: Dp? = null,
    val paddingX: Dp? = null,
    val fontSize: Dp? = null,
    val borderRadius: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCInputStyle(
    size: CCInputSize,
): CCInputStyle {
    var style = CCInputStyle()
    style = style.copy(borderColor = CocsoTokens.Color.borderPrimary())
    if (size == CCInputSize.xSmall) {
        style = style.copy(height = 28.dp)
        style = style.copy(paddingX = 8.dp)
        style = style.copy(fontSize = 12.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r3)
    }
    if (size == CCInputSize.small) {
        style = style.copy(height = 32.dp)
        style = style.copy(paddingX = 10.dp)
        style = style.copy(fontSize = 12.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r3)
    }
    if (size == CCInputSize.medium) {
        style = style.copy(height = 36.dp)
        style = style.copy(paddingX = 12.dp)
        style = style.copy(fontSize = 14.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (size == CCInputSize.large) {
        style = style.copy(height = 40.dp)
        style = style.copy(paddingX = 14.dp)
        style = style.copy(fontSize = 14.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    return style
}

enum class CCLinkVariant {
    inline,
    current,
    plain,
}

data class CCLinkStyle(
    val color: ComposeColor? = null,
)

@Composable
@ReadOnlyComposable
fun cCLinkStyle(
    variant: CCLinkVariant,
): CCLinkStyle {
    var style = CCLinkStyle()
    if (variant == CCLinkVariant.inline) {
        style = style.copy(color = CocsoTokens.Color.interactiveInfoText())
    }
    if (variant == CCLinkVariant.plain) {
        style = style.copy(color = CocsoTokens.Color.interactiveInfoText())
    }
    return style
}

enum class CCPaginationPageState {
    active,
    inactive,
    disabled,
}

data class CCPaginationStyle(
    val height: Dp? = null,
    val width: Dp? = null,
    val borderRadius: Dp? = null,
    val fontSize: Dp? = null,
    val bgColor: ComposeColor? = null,
    val fontColor: ComposeColor? = null,
    val fontWeight: FontWeight? = null,
)

@Composable
@ReadOnlyComposable
fun cCPaginationStyle(
    pageState: CCPaginationPageState,
): CCPaginationStyle {
    var style = CCPaginationStyle()
    style = style.copy(height = 32.dp)
    style = style.copy(width = 32.dp)
    style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    style = style.copy(fontSize = 14.dp)
    if (pageState == CCPaginationPageState.active) {
        style = style.copy(bgColor = CocsoTokens.Color.interactivePrimary())
        style = style.copy(fontColor = CocsoTokens.Color.textOnPrimary())
        style = style.copy(fontWeight = FontWeight.SemiBold)
    }
    if (pageState == CCPaginationPageState.inactive) {
        style = style.copy(fontColor = CocsoTokens.Color.textPrimary())
    }
    if (pageState == CCPaginationPageState.disabled) {
        style = style.copy(fontColor = CocsoTokens.Color.textDisabled())
    }
    return style
}

enum class CCProgressVariant {
    primary,
    secondary,
    success,
    danger,
    warning,
    info,
}

enum class CCProgressSize {
    sm,
    md,
    lg,
}

data class CCProgressStyle(
    val bgColor: ComposeColor? = null,
    val fillColor: ComposeColor? = null,
    val height: Dp? = null,
    val borderRadius: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCProgressStyle(
    variant: CCProgressVariant,
    size: CCProgressSize,
): CCProgressStyle {
    var style = CCProgressStyle()
    style = style.copy(bgColor = CocsoTokens.Color.surfaceNeutral())
    if (variant == CCProgressVariant.primary) {
        style = style.copy(fillColor = CocsoTokens.Color.interactivePrimary())
    }
    if (variant == CCProgressVariant.secondary) {
        style = style.copy(fillColor = CocsoTokens.Color.textMuted())
    }
    if (variant == CCProgressVariant.success) {
        style = style.copy(fillColor = CocsoTokens.Color.feedbackSuccess())
    }
    if (variant == CCProgressVariant.danger) {
        style = style.copy(fillColor = CocsoTokens.Color.feedbackDanger())
    }
    if (variant == CCProgressVariant.warning) {
        style = style.copy(fillColor = CocsoTokens.Color.feedbackWarning())
    }
    if (variant == CCProgressVariant.info) {
        style = style.copy(fillColor = CocsoTokens.Color.feedbackInfo())
    }
    if (size == CCProgressSize.sm) {
        style = style.copy(height = 4.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r1)
    }
    if (size == CCProgressSize.md) {
        style = style.copy(height = 8.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r2)
    }
    if (size == CCProgressSize.lg) {
        style = style.copy(height = 12.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r3)
    }
    return style
}

enum class CCRadioSize {
    large,
    medium,
    small,
}

enum class CCRadioSelected {
    `true`,
    `false`,
}

data class CCRadioStyle(
    val bgColor: ComposeColor? = null,
    val borderColor: ComposeColor? = null,
    val checkedColor: ComposeColor? = null,
    val focusRingColor: ComposeColor? = null,
    val size: Dp? = null,
    val dotSize: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCRadioStyle(
    size: CCRadioSize,
    selected: CCRadioSelected,
): CCRadioStyle {
    var style = CCRadioStyle()
    style = style.copy(bgColor = CocsoTokens.Color.surfacePrimary())
    style = style.copy(borderColor = CocsoTokens.Color.textPrimary())
    style = style.copy(checkedColor = CocsoTokens.Color.interactivePrimary())
    style = style.copy(focusRingColor = CocsoTokens.Color.focusRing())
    if (size == CCRadioSize.large) {
        style = style.copy(size = 18.dp)
        style = style.copy(dotSize = 8.dp)
    }
    if (size == CCRadioSize.medium) {
        style = style.copy(size = 16.dp)
        style = style.copy(dotSize = 7.dp)
    }
    if (size == CCRadioSize.small) {
        style = style.copy(size = 14.dp)
        style = style.copy(dotSize = 6.dp)
    }
    if (selected == CCRadioSelected.`true`) {
        style = style.copy(bgColor = CocsoTokens.Color.interactivePrimary())
        style = style.copy(borderColor = CocsoTokens.Color.interactivePrimary())
    }
    if (selected == CCRadioSelected.`false`) {
        style = style.copy(bgColor = CocsoTokens.Color.surfacePrimary())
        style = style.copy(borderColor = CocsoTokens.Color.borderPrimary())
    }
    return style
}

enum class CCSelectSize {
    xSmall,
    small,
    medium,
    large,
}

data class CCSelectStyle(
    val borderColor: ComposeColor? = null,
    val minWidth: Dp? = null,
    val height: Dp? = null,
    val paddingLeft: Dp? = null,
    val paddingRight: Dp? = null,
    val iconRight: Dp? = null,
    val fontSize: Dp? = null,
    val borderRadius: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCSelectStyle(
    size: CCSelectSize,
): CCSelectStyle {
    var style = CCSelectStyle()
    style = style.copy(borderColor = CocsoTokens.Color.borderPrimary())
    if (size == CCSelectSize.xSmall) {
        style = style.copy(minWidth = 28.dp)
        style = style.copy(height = 28.dp)
        style = style.copy(paddingLeft = 8.dp)
        style = style.copy(paddingRight = 26.dp)
        style = style.copy(iconRight = 8.dp)
        style = style.copy(fontSize = 12.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r3)
    }
    if (size == CCSelectSize.small) {
        style = style.copy(minWidth = 32.dp)
        style = style.copy(height = 32.dp)
        style = style.copy(paddingLeft = 10.dp)
        style = style.copy(paddingRight = 32.dp)
        style = style.copy(iconRight = 10.dp)
        style = style.copy(fontSize = 12.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r3)
    }
    if (size == CCSelectSize.medium) {
        style = style.copy(minWidth = 36.dp)
        style = style.copy(height = 36.dp)
        style = style.copy(paddingLeft = 12.dp)
        style = style.copy(paddingRight = 38.dp)
        style = style.copy(iconRight = 12.dp)
        style = style.copy(fontSize = 14.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    if (size == CCSelectSize.large) {
        style = style.copy(minWidth = 40.dp)
        style = style.copy(height = 40.dp)
        style = style.copy(paddingLeft = 14.dp)
        style = style.copy(paddingRight = 42.dp)
        style = style.copy(iconRight = 14.dp)
        style = style.copy(fontSize = 14.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    return style
}

enum class CCSkeletonVariant {
    text,
    circular,
    rectangular,
}

enum class CCSkeletonAnimation {
    pulse,
    wave,
    none,
}

data class CCSkeletonStyle(
    val bgColor: ComposeColor? = null,
    val height: Dp? = null,
    val borderRadius: Dp? = null,
    val width: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCSkeletonStyle(
    variant: CCSkeletonVariant,
    animation: CCSkeletonAnimation,
): CCSkeletonStyle {
    var style = CCSkeletonStyle()
    style = style.copy(bgColor = CocsoTokens.Color.surfaceNeutral())
    if (variant == CCSkeletonVariant.text) {
        style = style.copy(height = 16.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r2)
    }
    if (variant == CCSkeletonVariant.circular) {
        style = style.copy(height = 40.dp)
        style = style.copy(width = 40.dp)
    }
    if (variant == CCSkeletonVariant.rectangular) {
        style = style.copy(height = 120.dp)
        style = style.copy(borderRadius = CocsoTokens.Radius.r4)
    }
    return style
}

enum class CCSpinnerVariant {
    primary,
    secondary,
    success,
    error,
    warning,
    info,
    white,
}

enum class CCSpinnerSize {
    large,
    medium,
    small,
}

data class CCSpinnerStyle(
    val bladeColor: ComposeColor? = null,
    val blades: Dp? = null,
    val bladeWidth: Dp? = null,
    val bladeHeight: Dp? = null,
    val output: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCSpinnerStyle(
    variant: CCSpinnerVariant,
    size: CCSpinnerSize,
): CCSpinnerStyle {
    var style = CCSpinnerStyle()
    if (variant == CCSpinnerVariant.primary) {
        style = style.copy(bladeColor = CocsoTokens.Color.interactivePrimary())
    }
    if (variant == CCSpinnerVariant.secondary) {
        style = style.copy(bladeColor = CocsoTokens.Color.textMuted())
    }
    if (variant == CCSpinnerVariant.success) {
        style = style.copy(bladeColor = CocsoTokens.Color.feedbackSuccess())
    }
    if (variant == CCSpinnerVariant.error) {
        style = style.copy(bladeColor = CocsoTokens.Color.feedbackDanger())
    }
    if (variant == CCSpinnerVariant.warning) {
        style = style.copy(bladeColor = CocsoTokens.Color.feedbackWarning())
    }
    if (variant == CCSpinnerVariant.info) {
        style = style.copy(bladeColor = CocsoTokens.Color.feedbackInfo())
    }
    if (variant == CCSpinnerVariant.white) {
        style = style.copy(bladeColor = CocsoTokens.Color.surfacePrimary())
    }
    if (size == CCSpinnerSize.large) {
        style = style.copy(blades = 10.dp)
        style = style.copy(bladeWidth = 2.dp)
        style = style.copy(bladeHeight = 6.dp)
        style = style.copy(output = 20.dp)
    }
    if (size == CCSpinnerSize.medium) {
        style = style.copy(blades = 8.dp)
        style = style.copy(bladeWidth = 2.dp)
        style = style.copy(bladeHeight = 5.dp)
        style = style.copy(output = 16.dp)
    }
    if (size == CCSpinnerSize.small) {
        style = style.copy(blades = 6.dp)
        style = style.copy(bladeWidth = 1.5.dp)
        style = style.copy(bladeHeight = 4.dp)
        style = style.copy(output = 12.dp)
    }
    return style
}

enum class CCStockQuantityStatusQuantity {
    sufficient,
    normal,
    insufficient,
}

data class CCStockQuantityStatusStyle(
    val color: ComposeColor? = null,
)

@Composable
@ReadOnlyComposable
fun cCStockQuantityStatusStyle(
    quantity: CCStockQuantityStatusQuantity,
): CCStockQuantityStatusStyle {
    var style = CCStockQuantityStatusStyle()
    if (quantity == CCStockQuantityStatusQuantity.sufficient) {
        style = style.copy(color = CocsoTokens.Color.feedbackInfoText())
    }
    if (quantity == CCStockQuantityStatusQuantity.normal) {
        style = style.copy(color = CocsoTokens.Color.feedbackSuccessText())
    }
    if (quantity == CCStockQuantityStatusQuantity.insufficient) {
        style = style.copy(color = CocsoTokens.Color.feedbackDangerText())
    }
    return style
}

enum class CCSwitchVariant {
    primary,
    success,
    error,
    warning,
    info,
}

enum class CCSwitchSize {
    large,
    medium,
    small,
}

enum class CCSwitchChecked {
    `true`,
    `false`,
}

data class CCSwitchStyle(
    val switchBgColor: ComposeColor? = null,
    val checkedBgColor: ComposeColor? = null,
    val width: Dp? = null,
    val height: Dp? = null,
    val thumbSize: Dp? = null,
    val thumbOffset: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCSwitchStyle(
    variant: CCSwitchVariant,
    size: CCSwitchSize,
    checked: CCSwitchChecked,
): CCSwitchStyle {
    var style = CCSwitchStyle()
    style = style.copy(switchBgColor = CocsoTokens.Color.surfaceNeutral())
    if (variant == CCSwitchVariant.primary) {
        style = style.copy(checkedBgColor = CocsoTokens.Color.interactivePrimary())
    }
    if (variant == CCSwitchVariant.success) {
        style = style.copy(checkedBgColor = CocsoTokens.Color.interactiveSuccess())
    }
    if (variant == CCSwitchVariant.error) {
        style = style.copy(checkedBgColor = CocsoTokens.Color.interactiveDanger())
    }
    if (variant == CCSwitchVariant.warning) {
        style = style.copy(checkedBgColor = CocsoTokens.Color.interactiveWarningActive())
    }
    if (variant == CCSwitchVariant.info) {
        style = style.copy(checkedBgColor = CocsoTokens.Color.interactiveInfo())
    }
    if (size == CCSwitchSize.large) {
        style = style.copy(width = 40.dp)
        style = style.copy(height = 22.dp)
        style = style.copy(thumbSize = 18.dp)
        style = style.copy(thumbOffset = 2.dp)
    }
    if (size == CCSwitchSize.medium) {
        style = style.copy(width = 36.dp)
        style = style.copy(height = 20.dp)
        style = style.copy(thumbSize = 16.dp)
        style = style.copy(thumbOffset = 2.dp)
    }
    if (size == CCSwitchSize.small) {
        style = style.copy(width = 32.dp)
        style = style.copy(height = 18.dp)
        style = style.copy(thumbSize = 14.dp)
        style = style.copy(thumbOffset = 2.dp)
    }
    if (variant == CCSwitchVariant.primary && checked == CCSwitchChecked.`true`) {
        style = style.copy(switchBgColor = CocsoTokens.Color.interactivePrimary())
    }
    if (variant == CCSwitchVariant.success && checked == CCSwitchChecked.`true`) {
        style = style.copy(switchBgColor = CocsoTokens.Color.interactiveSuccess())
    }
    if (variant == CCSwitchVariant.error && checked == CCSwitchChecked.`true`) {
        style = style.copy(switchBgColor = CocsoTokens.Color.interactiveDanger())
    }
    if (variant == CCSwitchVariant.warning && checked == CCSwitchChecked.`true`) {
        style = style.copy(switchBgColor = CocsoTokens.Color.interactiveWarningActive())
    }
    if (variant == CCSwitchVariant.info && checked == CCSwitchChecked.`true`) {
        style = style.copy(switchBgColor = CocsoTokens.Color.interactiveInfo())
    }
    return style
}

enum class CCTypographyType {
    body,
    heading,
}

enum class CCTypographySize {
    xLarge,
    large,
    medium,
    small,
    xSmall,
}

data class CCTypographyStyle(
    val fontWeight: FontWeight? = null,
    val fontSize: Dp? = null,
)

@Composable
@ReadOnlyComposable
fun cCTypographyStyle(
    type: CCTypographyType,
    size: CCTypographySize,
): CCTypographyStyle {
    var style = CCTypographyStyle()
    if (type == CCTypographyType.heading) {
        style = style.copy(fontWeight = FontWeight.Bold)
    }
    if (size == CCTypographySize.xLarge) {
        style = style.copy(fontSize = 28.dp)
    }
    if (size == CCTypographySize.large) {
        style = style.copy(fontSize = 24.dp)
    }
    if (size == CCTypographySize.medium) {
        style = style.copy(fontSize = 20.dp)
    }
    if (size == CCTypographySize.small) {
        style = style.copy(fontSize = 16.dp)
    }
    if (size == CCTypographySize.xSmall) {
        style = style.copy(fontSize = 14.dp)
    }
    if (type == CCTypographyType.body && size == CCTypographySize.xLarge) {
        style = style.copy(fontSize = 18.dp)
    }
    if (type == CCTypographyType.body && size == CCTypographySize.large) {
        style = style.copy(fontSize = 18.dp)
    }
    if (type == CCTypographyType.body && size == CCTypographySize.medium) {
        style = style.copy(fontSize = 16.dp)
    }
    if (type == CCTypographyType.body && size == CCTypographySize.small) {
        style = style.copy(fontSize = 14.dp)
    }
    if (type == CCTypographyType.body && size == CCTypographySize.xSmall) {
        style = style.copy(fontSize = 12.dp)
    }
    return style
}
