// Generated by @cocso-ui/baseframe — do not edit.
// Source: packages/baseframe-sources
// Regenerate: pnpm --filter @cocso-ui/baseframe generate:mobile

package ai.cocso.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.ui.graphics.Color as ComposeColor
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object CocsoBrandCocso {
    object Color {

        // Resolved against the system theme, so a caller cannot render
        // light tokens in a dark window by forgetting to pass a flag.
        @Composable
        @ReadOnlyComposable
        fun borderSecondary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF3A3E46) else ComposeColor(0xFFE6E8EA)
        @Composable
        @ReadOnlyComposable
        fun feedbackDangerBorder(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFDE3412) else ComposeColor(0xFFF7AFA1)
        @Composable
        @ReadOnlyComposable
        fun feedbackDangerSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF493231) else ComposeColor(0xFFFDEFEC)
        @Composable
        @ReadOnlyComposable
        fun feedbackInfoBorder(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF256EF4) else ComposeColor(0xFFB1CEFB)
        @Composable
        @ReadOnlyComposable
        fun feedbackInfoSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF2B3951) else ComposeColor(0xFFECF2FE)
        @Composable
        @ReadOnlyComposable
        fun feedbackSuccessBorder(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF228738) else ComposeColor(0xFFA9DAB4)
        @Composable
        @ReadOnlyComposable
        fun feedbackSuccessSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF293F34) else ComposeColor(0xFFEAF6EC)
        @Composable
        @ReadOnlyComposable
        fun feedbackWarningBorder(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF9E6A00) else ComposeColor(0xFFFFC95C)
        @Composable
        @ReadOnlyComposable
        fun feedbackWarningSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF413925) else ComposeColor(0xFFFFF3DB)
        @Composable
        @ReadOnlyComposable
        fun feedbackWarningText(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFE49410) else ComposeColor(0xFF8A5C00)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF2260D3) else ComposeColor(0xFF256EF4)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimaryActive(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF083891) else ComposeColor(0xFF083891)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimaryHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF0B50D0) else ComposeColor(0xFF0B50D0)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimaryMuted(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF1E2A45) else ComposeColor(0xFFB1CEFB)
        @Composable
        @ReadOnlyComposable
        fun primary100(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFD8E5FD) else ComposeColor(0xFFD8E5FD)
        @Composable
        @ReadOnlyComposable
        fun primary200(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFB1CEFB) else ComposeColor(0xFFB1CEFB)
        @Composable
        @ReadOnlyComposable
        fun primary300(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF86AFF9) else ComposeColor(0xFF86AFF9)
        @Composable
        @ReadOnlyComposable
        fun primary400(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF4C87F6) else ComposeColor(0xFF4C87F6)
        @Composable
        @ReadOnlyComposable
        fun primary50(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFECF2FE) else ComposeColor(0xFFECF2FE)
        @Composable
        @ReadOnlyComposable
        fun primary500(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF256EF4) else ComposeColor(0xFF256EF4)
        @Composable
        @ReadOnlyComposable
        fun primary600(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF0B50D0) else ComposeColor(0xFF0B50D0)
        @Composable
        @ReadOnlyComposable
        fun primary700(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF083891) else ComposeColor(0xFF083891)
        @Composable
        @ReadOnlyComposable
        fun primary800(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF052561) else ComposeColor(0xFF052561)
        @Composable
        @ReadOnlyComposable
        fun primary900(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF03163A) else ComposeColor(0xFF03163A)
        @Composable
        @ReadOnlyComposable
        fun primary950(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF020F27) else ComposeColor(0xFF020F27)
        @Composable
        @ReadOnlyComposable
        fun surfacePrimary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF1A1D21) else ComposeColor(0xFFFFFFFF)
        @Composable
        @ReadOnlyComposable
        fun surfaceSecondary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF24282D) else ComposeColor(0xFFF4F5F6)
        @Composable
        @ReadOnlyComposable
        fun textOnPrimary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFFFFFFF) else ComposeColor(0xFFFFFFFF)
    }

}
