// Generated by @cocso-ui/baseframe — do not edit.
// Source: packages/baseframe-sources
// Regenerate: pnpm --filter @cocso-ui/baseframe generate:mobile

package ai.cocso.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.ui.graphics.Color as ComposeColor
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

object CocsoTokens {
    object Color {
        val black: ComposeColor = ComposeColor(0xFF000000)
        val blackAlpha10: ComposeColor = ComposeColor(0x1A000000)
        val blackAlpha20: ComposeColor = ComposeColor(0x33000000)
        val blackAlpha30: ComposeColor = ComposeColor(0x4D000000)
        val blackAlpha40: ComposeColor = ComposeColor(0x66000000)
        val blackAlpha5: ComposeColor = ComposeColor(0x0D000000)
        val blackAlpha50: ComposeColor = ComposeColor(0x80000000)
        val blackAlpha60: ComposeColor = ComposeColor(0x99000000)
        val blackAlpha70: ComposeColor = ComposeColor(0xB3000000)
        val blackAlpha80: ComposeColor = ComposeColor(0xCC000000)
        val blackAlpha90: ComposeColor = ComposeColor(0xE6000000)
        val danger100: ComposeColor = ComposeColor(0xFFFCDFD9)
        val danger200: ComposeColor = ComposeColor(0xFFF7AFA1)
        val danger300: ComposeColor = ComposeColor(0xFFF48771)
        val danger400: ComposeColor = ComposeColor(0xFFF05F42)
        val danger50: ComposeColor = ComposeColor(0xFFFDEFEC)
        val danger500: ComposeColor = ComposeColor(0xFFDE3412)
        val danger600: ComposeColor = ComposeColor(0xFFBD2C0F)
        val danger700: ComposeColor = ComposeColor(0xFF8A240F)
        val danger800: ComposeColor = ComposeColor(0xFF5C180A)
        val danger900: ComposeColor = ComposeColor(0xFF390D05)
        val danger950: ComposeColor = ComposeColor(0xFF260903)
        val info100: ComposeColor = ComposeColor(0xFFD8E5FD)
        val info200: ComposeColor = ComposeColor(0xFFB1CEFB)
        val info300: ComposeColor = ComposeColor(0xFF86AFF9)
        val info400: ComposeColor = ComposeColor(0xFF4C87F6)
        val info50: ComposeColor = ComposeColor(0xFFECF2FE)
        val info500: ComposeColor = ComposeColor(0xFF256EF4)
        val info600: ComposeColor = ComposeColor(0xFF0B50D0)
        val info700: ComposeColor = ComposeColor(0xFF083891)
        val info800: ComposeColor = ComposeColor(0xFF052561)
        val info900: ComposeColor = ComposeColor(0xFF03163A)
        val info950: ComposeColor = ComposeColor(0xFF020F27)
        val neutral100: ComposeColor = ComposeColor(0xFFE6E8EA)
        val neutral200: ComposeColor = ComposeColor(0xFFCDD1D5)
        val neutral300: ComposeColor = ComposeColor(0xFFB1B8BE)
        val neutral400: ComposeColor = ComposeColor(0xFF8A949E)
        val neutral50: ComposeColor = ComposeColor(0xFFF4F5F6)
        val neutral500: ComposeColor = ComposeColor(0xFF6D7882)
        val neutral600: ComposeColor = ComposeColor(0xFF58616A)
        val neutral700: ComposeColor = ComposeColor(0xFF464C53)
        val neutral800: ComposeColor = ComposeColor(0xFF33363D)
        val neutral900: ComposeColor = ComposeColor(0xFF1E2124)
        val neutral950: ComposeColor = ComposeColor(0xFF131416)
        val primary100: ComposeColor = ComposeColor(0xFFE6E8EA)
        val primary200: ComposeColor = ComposeColor(0xFFCDD1D5)
        val primary300: ComposeColor = ComposeColor(0xFFB1B8BE)
        val primary400: ComposeColor = ComposeColor(0xFF8A949E)
        val primary50: ComposeColor = ComposeColor(0xFFF4F5F6)
        val primary500: ComposeColor = ComposeColor(0xFF6D7882)
        val primary600: ComposeColor = ComposeColor(0xFF58616A)
        val primary700: ComposeColor = ComposeColor(0xFF464C53)
        val primary800: ComposeColor = ComposeColor(0xFF33363D)
        val primary900: ComposeColor = ComposeColor(0xFF1E2124)
        val primary950: ComposeColor = ComposeColor(0xFF131416)
        val success100: ComposeColor = ComposeColor(0xFFD8EEDD)
        val success200: ComposeColor = ComposeColor(0xFFA9DAB4)
        val success300: ComposeColor = ComposeColor(0xFF7EC88E)
        val success400: ComposeColor = ComposeColor(0xFF3FA654)
        val success50: ComposeColor = ComposeColor(0xFFEAF6EC)
        val success500: ComposeColor = ComposeColor(0xFF228738)
        val success600: ComposeColor = ComposeColor(0xFF267337)
        val success700: ComposeColor = ComposeColor(0xFF285D33)
        val success800: ComposeColor = ComposeColor(0xFF1F4727)
        val success900: ComposeColor = ComposeColor(0xFF122B18)
        val success950: ComposeColor = ComposeColor(0xFF0E2012)
        val warning100: ComposeColor = ComposeColor(0xFFFFE0A3)
        val warning200: ComposeColor = ComposeColor(0xFFFFC95C)
        val warning300: ComposeColor = ComposeColor(0xFFFFB114)
        val warning400: ComposeColor = ComposeColor(0xFFC78500)
        val warning50: ComposeColor = ComposeColor(0xFFFFF3DB)
        val warning500: ComposeColor = ComposeColor(0xFF9E6A00)
        val warning600: ComposeColor = ComposeColor(0xFF8A5C00)
        val warning700: ComposeColor = ComposeColor(0xFF614100)
        val warning800: ComposeColor = ComposeColor(0xFF422C00)
        val warning900: ComposeColor = ComposeColor(0xFF2E1F00)
        val warning950: ComposeColor = ComposeColor(0xFF241800)
        val white: ComposeColor = ComposeColor(0xFFFFFFFF)
        val whiteAlpha10: ComposeColor = ComposeColor(0x1AFFFFFF)
        val whiteAlpha20: ComposeColor = ComposeColor(0x33FFFFFF)
        val whiteAlpha30: ComposeColor = ComposeColor(0x4DFFFFFF)
        val whiteAlpha40: ComposeColor = ComposeColor(0x66FFFFFF)
        val whiteAlpha5: ComposeColor = ComposeColor(0x0DFFFFFF)
        val whiteAlpha50: ComposeColor = ComposeColor(0x80FFFFFF)
        val whiteAlpha60: ComposeColor = ComposeColor(0x99FFFFFF)
        val whiteAlpha70: ComposeColor = ComposeColor(0xB3FFFFFF)
        val whiteAlpha80: ComposeColor = ComposeColor(0xCCFFFFFF)
        val whiteAlpha90: ComposeColor = ComposeColor(0xE6FFFFFF)

        // Resolved against the system theme, so a caller cannot render
        // light tokens in a dark window by forgetting to pass a flag.
        @Composable
        @ReadOnlyComposable
        fun alphaShadow1(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0x3D000000) else ComposeColor(0x0A000000)
        @Composable
        @ReadOnlyComposable
        fun alphaShadow2(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0x5C000000) else ComposeColor(0x14000000)
        @Composable
        @ReadOnlyComposable
        fun alphaShadow3(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0x7A000000) else ComposeColor(0x1F000000)
        @Composable
        @ReadOnlyComposable
        fun borderPrimary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF464C53) else ComposeColor(0xFFCDD1D5)
        @Composable
        @ReadOnlyComposable
        fun borderSecondary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF33363D) else ComposeColor(0xFFE6E8EA)
        @Composable
        @ReadOnlyComposable
        fun borderStrong(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF6D7882) else ComposeColor(0xFF6D7882)
        @Composable
        @ReadOnlyComposable
        fun feedbackDanger(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFF05F42) else ComposeColor(0xFFDE3412)
        @Composable
        @ReadOnlyComposable
        fun feedbackDangerBorder(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF5C180A) else ComposeColor(0xFFF7AFA1)
        @Composable
        @ReadOnlyComposable
        fun feedbackDangerSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF260903) else ComposeColor(0xFFFDEFEC)
        @Composable
        @ReadOnlyComposable
        fun feedbackDangerText(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFF48771) else ComposeColor(0xFFBD2C0F)
        @Composable
        @ReadOnlyComposable
        fun feedbackInfo(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF4C87F6) else ComposeColor(0xFF256EF4)
        @Composable
        @ReadOnlyComposable
        fun feedbackInfoBorder(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF052561) else ComposeColor(0xFFB1CEFB)
        @Composable
        @ReadOnlyComposable
        fun feedbackInfoSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF020F27) else ComposeColor(0xFFECF2FE)
        @Composable
        @ReadOnlyComposable
        fun feedbackInfoText(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF86AFF9) else ComposeColor(0xFF0B50D0)
        @Composable
        @ReadOnlyComposable
        fun feedbackSuccess(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF3FA654) else ComposeColor(0xFF228738)
        @Composable
        @ReadOnlyComposable
        fun feedbackSuccessBorder(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF1F4727) else ComposeColor(0xFFA9DAB4)
        @Composable
        @ReadOnlyComposable
        fun feedbackSuccessMuted(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF3FA654) else ComposeColor(0xFF3FA654)
        @Composable
        @ReadOnlyComposable
        fun feedbackSuccessSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF0E2012) else ComposeColor(0xFFEAF6EC)
        @Composable
        @ReadOnlyComposable
        fun feedbackSuccessText(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF7EC88E) else ComposeColor(0xFF267337)
        @Composable
        @ReadOnlyComposable
        fun feedbackWarning(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFC78500) else ComposeColor(0xFF9E6A00)
        @Composable
        @ReadOnlyComposable
        fun feedbackWarningBorder(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF422C00) else ComposeColor(0xFFFFC95C)
        @Composable
        @ReadOnlyComposable
        fun feedbackWarningSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF241800) else ComposeColor(0xFFFFF3DB)
        @Composable
        @ReadOnlyComposable
        fun feedbackWarningText(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFFFB114) else ComposeColor(0xFF8A5C00)
        @Composable
        @ReadOnlyComposable
        fun focusRing(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFF4F5F6) else ComposeColor(0xFF131416)
        @Composable
        @ReadOnlyComposable
        fun interactiveDanger(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFDE3412) else ComposeColor(0xFFDE3412)
        @Composable
        @ReadOnlyComposable
        fun interactiveDangerActive(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF8A240F) else ComposeColor(0xFF8A240F)
        @Composable
        @ReadOnlyComposable
        fun interactiveDangerHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFBD2C0F) else ComposeColor(0xFFBD2C0F)
        @Composable
        @ReadOnlyComposable
        fun interactiveDangerHoverSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFF05F42) else ComposeColor(0xFFF05F42)
        @Composable
        @ReadOnlyComposable
        fun interactiveDangerSubtleActive(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF390D05) else ComposeColor(0xFFFCDFD9)
        @Composable
        @ReadOnlyComposable
        fun interactiveDangerSubtleHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF260903) else ComposeColor(0xFFFDEFEC)
        @Composable
        @ReadOnlyComposable
        fun interactiveInfo(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF256EF4) else ComposeColor(0xFF256EF4)
        @Composable
        @ReadOnlyComposable
        fun interactiveInfoActive(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF083891) else ComposeColor(0xFF083891)
        @Composable
        @ReadOnlyComposable
        fun interactiveInfoHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF0B50D0) else ComposeColor(0xFF0B50D0)
        @Composable
        @ReadOnlyComposable
        fun interactiveInfoHoverSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF4C87F6) else ComposeColor(0xFF4C87F6)
        @Composable
        @ReadOnlyComposable
        fun interactiveInfoText(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF86AFF9) else ComposeColor(0xFF0B50D0)
        @Composable
        @ReadOnlyComposable
        fun interactiveInfoTextHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFB1CEFB) else ComposeColor(0xFF083891)
        @Composable
        @ReadOnlyComposable
        fun interactiveNeutral(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF33363D) else ComposeColor(0xFFE6E8EA)
        @Composable
        @ReadOnlyComposable
        fun interactiveNeutralActive(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF58616A) else ComposeColor(0xFFB1B8BE)
        @Composable
        @ReadOnlyComposable
        fun interactiveNeutralHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF464C53) else ComposeColor(0xFFCDD1D5)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFF4F5F6) else ComposeColor(0xFF131416)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimaryActive(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFB1B8BE) else ComposeColor(0xFF464C53)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimaryHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFCDD1D5) else ComposeColor(0xFF33363D)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimaryMuted(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF6D7882) else ComposeColor(0xFF6D7882)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimarySubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF1E2124) else ComposeColor(0xFFE6E8EA)
        @Composable
        @ReadOnlyComposable
        fun interactivePrimaryText(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFCDD1D5) else ComposeColor(0xFF33363D)
        @Composable
        @ReadOnlyComposable
        fun interactiveSecondary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF33363D) else ComposeColor(0xFFE6E8EA)
        @Composable
        @ReadOnlyComposable
        fun interactiveSecondaryHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF464C53) else ComposeColor(0xFFCDD1D5)
        @Composable
        @ReadOnlyComposable
        fun interactiveSuccess(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF228738) else ComposeColor(0xFF228738)
        @Composable
        @ReadOnlyComposable
        fun interactiveSuccessActive(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF285D33) else ComposeColor(0xFF285D33)
        @Composable
        @ReadOnlyComposable
        fun interactiveSuccessHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF267337) else ComposeColor(0xFF267337)
        @Composable
        @ReadOnlyComposable
        fun interactiveSuccessHoverSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF3FA654) else ComposeColor(0xFF3FA654)
        @Composable
        @ReadOnlyComposable
        fun interactiveWarning(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFFFB114) else ComposeColor(0xFFFFB114)
        @Composable
        @ReadOnlyComposable
        fun interactiveWarningActive(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF9E6A00) else ComposeColor(0xFF9E6A00)
        @Composable
        @ReadOnlyComposable
        fun interactiveWarningHover(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFC78500) else ComposeColor(0xFFC78500)
        @Composable
        @ReadOnlyComposable
        fun interactiveWarningHoverSubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFC78500) else ComposeColor(0xFFC78500)
        @Composable
        @ReadOnlyComposable
        fun overlayMuted(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0x1AFFFFFF) else ComposeColor(0x1A000000)
        @Composable
        @ReadOnlyComposable
        fun overlayStrong(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0x33FFFFFF) else ComposeColor(0x33000000)
        @Composable
        @ReadOnlyComposable
        fun overlaySubtle(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0x0DFFFFFF) else ComposeColor(0x0D000000)
        @Composable
        @ReadOnlyComposable
        fun surfaceInverse(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFFFFFFF) else ComposeColor(0xFF131416)
        @Composable
        @ReadOnlyComposable
        fun surfaceNeutral(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF33363D) else ComposeColor(0xFFE6E8EA)
        @Composable
        @ReadOnlyComposable
        fun surfacePrimary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF131416) else ComposeColor(0xFFFFFFFF)
        @Composable
        @ReadOnlyComposable
        fun surfaceSecondary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF1E2124) else ComposeColor(0xFFF4F5F6)
        @Composable
        @ReadOnlyComposable
        fun textDisabled(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF58616A) else ComposeColor(0xFF8A949E)
        @Composable
        @ReadOnlyComposable
        fun textMuted(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF6D7882) else ComposeColor(0xFF6D7882)
        @Composable
        @ReadOnlyComposable
        fun textOnDanger(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFFFFFFF) else ComposeColor(0xFFFFFFFF)
        @Composable
        @ReadOnlyComposable
        fun textOnInfo(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFFFFFFF) else ComposeColor(0xFFFFFFFF)
        @Composable
        @ReadOnlyComposable
        fun textOnPrimary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF131416) else ComposeColor(0xFFFFFFFF)
        @Composable
        @ReadOnlyComposable
        fun textOnSuccess(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFFFFFFF) else ComposeColor(0xFFFFFFFF)
        @Composable
        @ReadOnlyComposable
        fun textOnWarning(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF131416) else ComposeColor(0xFF131416)
        @Composable
        @ReadOnlyComposable
        fun textPrimary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFFF4F5F6) else ComposeColor(0xFF131416)
        @Composable
        @ReadOnlyComposable
        fun textSecondary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF8A949E) else ComposeColor(0xFF58616A)
        @Composable
        @ReadOnlyComposable
        fun textTertiary(): ComposeColor =
            if (isSystemInDarkTheme()) ComposeColor(0xFF6D7882) else ComposeColor(0xFF8A949E)
    }

    object Text {
        val base: Dp = 16.dp
        val sm: Dp = 14.dp
        val xs: Dp = 12.dp
    }

    object FontWeight {
        val black: Dp = 900.dp
        val bold: Dp = 700.dp
        val extrabold: Dp = 800.dp
        val extralight: Dp = 200.dp
        val light: Dp = 300.dp
        val medium: Dp = 500.dp
        val regular: Dp = 400.dp
        val semibold: Dp = 600.dp
        val thin: Dp = 100.dp
    }

    object Radius {
        val full: Dp = 1000.dp
        val r1: Dp = 2.dp
        val r2: Dp = 4.dp
        val r3: Dp = 6.dp
        val r4: Dp = 8.dp
        val r5: Dp = 12.dp
        val r6: Dp = 16.dp
    }

    object Shadow {
        val blur3: Dp = 16.dp
        val blur4: Dp = 24.dp
        val y3: Dp = 8.dp
        val y4: Dp = 16.dp
    }

    object Spacing {
        val max: Dp = 1000.dp
        val s0: Dp = 0.dp
        val s1: Dp = 1.dp
        val s10: Dp = 24.dp
        val s11: Dp = 28.dp
        val s12: Dp = 32.dp
        val s13: Dp = 36.dp
        val s14: Dp = 40.dp
        val s15: Dp = 44.dp
        val s16: Dp = 48.dp
        val s17: Dp = 56.dp
        val s18: Dp = 64.dp
        val s19: Dp = 72.dp
        val s2: Dp = 2.dp
        val s20: Dp = 80.dp
        val s21: Dp = 96.dp
        val s3: Dp = 4.dp
        val s4: Dp = 6.dp
        val s5: Dp = 8.dp
        val s6: Dp = 10.dp
        val s7: Dp = 12.dp
        val s8: Dp = 16.dp
        val s9: Dp = 20.dp
    }

    object ZIndex {
        val above: Dp = 1.dp
        val base: Dp = 0.dp
        val behind: Dp = -1.dp
        val dialog: Dp = 200.dp
        val dialogContent: Dp = 250.dp
        val header: Dp = 50.dp
        val overlay: Dp = 100.dp
        val popover: Dp = 300.dp
        val tooltip: Dp = 400.dp
    }

    object Duration {
        val decorative: Dp = 0.75.dp
        val decorativeSlow: Dp = 1.5.dp
        val fast: Dp = 0.15.dp
        val normal: Dp = 0.2.dp
        val slow: Dp = 0.25.dp
    }

}
