import type { Ast, TokenDecl } from "../types";

/**
 * Swift and Kotlin token emitters.
 *
 * CSS can defer: `--cocso-color-text-primary: var(--cocso-color-neutral-950)`
 * leaves the indirection to the browser, and the dark theme redefines one end
 * of it. Neither platform here has that, so a token has to arrive as a value —
 * every reference chain resolved, once per mode.
 *
 * That is also why this lives beside the CSS emitters rather than in a script
 * that reads the YAML. `cocso/mobile` had such a script, and when the semantic
 * colours moved from one mode to two it did not fail: it kept reading
 * `values.default`, found nothing, and emitted four colours instead of
 * fifty-nine. Emitting from the validated AST means a token missing a value for
 * a mode its collection declares is rejected before it reaches here.
 */

export interface MobileOptions {
  /**
   * Emit only tokens from these collections. The others stay in the AST for
   * reference resolution — a brand overlay declares `$color.interactive.primary`
   * as `$color.info-500`, so the primitives must be present to resolve it, but
   * must not be emitted again alongside it.
   */
  only?: string[];
  /** Kotlin only. */
  packageName?: string;
  /** Swift: the enclosing type. Kotlin: the object name. */
  typeName?: string;
}

export interface MobileOutput {
  kotlin: string;
  /** Tokens deliberately not emitted, with the reason. */
  skipped: { name: string; reason: string }[];
  swift: string;
}

const HEADER = [
  "// Generated by @cocso-ui/baseframe — do not edit.",
  "// Source: packages/baseframe-sources",
  "// Regenerate: pnpm --filter @cocso-ui/baseframe generate:mobile",
].join("\n");

const TOKEN_REF = /^\$[a-z0-9-]+\./i;
const HEX = /^#([0-9a-f]{6})$/i;
const PX = /^(-?\d+(?:\.\d+)?)px$/;
const SECONDS = /^(-?\d+(?:\.\d+)?)s$/;
const PLAIN_NUMBER = /^-?\d+(?:\.\d+)?$/;
const NAME_SEPARATORS = /[.\-_]/;
const LEADING_DIGIT = /^\d/;
const DOLLAR_PREFIX = /^\$/;
const RGBA =
  /^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/;
const CUBIC_BEZIER =
  /^cubic-bezier\(\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\)$/;

/**
 * The CSS easing keywords, as the control points the specification defines
 * them by. Both platforms take a cubic Bézier and neither takes the keyword,
 * so the curve is what crosses.
 */
const NAMED_EASINGS: Record<string, Curve> = {
  ease: [0.25, 0.1, 0.25, 1],
  "ease-in": [0.42, 0, 1, 1],
  "ease-in-out": [0.42, 0, 0.58, 1],
  "ease-out": [0, 0, 0.58, 1],
  linear: [0, 0, 1, 1],
};

/** Swift's keywords a token name can collide with — `$easing.default`. */
const SWIFT_RESERVED = new Set(["default", "in", "is", "as", "for", "static"]);

function toHex(n: number): string {
  return Math.max(0, Math.min(255, Math.round(n)))
    .toString(16)
    .toUpperCase()
    .padStart(2, "0");
}

type Curve = [number, number, number, number];

/** A value the platforms can hold, once every reference is followed. */
type Resolved =
  | { kind: "color"; hex: string; alpha: number }
  | { kind: "number"; value: number }
  /** A cubic Bézier easing — `$easing.*`. */
  | { kind: "curve"; points: Curve };

/**
 * Follow `$color.text.primary` → `$color.neutral-950` → `#131416`.
 *
 * A reference is resolved in the mode being emitted, falling back to `default`
 * — the ramps live in a single-mode collection, so a themed token reaching one
 * lands on its only value rather than failing to find a `light`.
 */
function resolve(
  name: string,
  mode: string,
  byName: Map<string, TokenDecl>,
  seen = new Set<string>()
): string | number | null {
  if (seen.has(name)) {
    throw new Error(`Circular token reference: ${[...seen, name].join(" → ")}`);
  }
  seen.add(name);

  const token = byName.get(name);
  if (!token) {
    return null;
  }
  const value =
    token.values.find((v) => v.mode === mode)?.value ??
    token.values.find((v) => v.mode === "default")?.value;
  if (value === undefined) {
    return null;
  }
  if (typeof value === "string" && TOKEN_REF.test(value)) {
    return resolve(value, mode, byName, seen);
  }
  return value;
}

function classify(value: string | number | null): Resolved | string {
  if (value === null) {
    return "unresolved reference";
  }
  if (typeof value === "number") {
    return { kind: "number", value };
  }
  const hex = value.match(HEX);
  if (hex) {
    return { alpha: 1, hex: hex[1].toUpperCase(), kind: "color" };
  }
  // Both platforms hold alpha in a colour perfectly well — SwiftUI takes an
  // opacity, Compose takes AARRGGBB. An earlier version of this file skipped
  // them and said neither could, which was not a fact about the platforms but
  // about the converter it replaced. Dropping them would take the whole
  // `overlay-*` role, whose entire job is a translucent tint, off mobile.
  const rgba = value.match(RGBA);
  if (rgba) {
    const [, r, g, b, a] = rgba;
    return {
      alpha: a === undefined ? 1 : Number(a),
      hex: toHex(Number(r)) + toHex(Number(g)) + toHex(Number(b)),
      kind: "color",
    };
  }
  const px = value.match(PX);
  if (px) {
    return { kind: "number", value: Number(px[1]) };
  }
  const seconds = value.match(SECONDS);
  if (seconds) {
    return { kind: "number", value: Number(seconds[1]) };
  }
  // Easing. `ease-in-out` was "unsupported" and `cubic-bezier(...)` was a
  // "composite value" — so the motion the web runs on reached neither platform
  // and each view picked a duration and a curve of its own.
  const named = NAMED_EASINGS[value];
  if (named) {
    return { kind: "curve", points: named };
  }
  const bezier = value.match(CUBIC_BEZIER);
  if (bezier) {
    const [, a, b, c, d] = bezier;
    return { kind: "curve", points: [Number(a), Number(b), Number(c), Number(d)] };
  }
  // YAML quotes some scales, so a plain number can arrive as a string.
  if (PLAIN_NUMBER.test(value)) {
    return { kind: "number", value: Number(value) };
  }
  if (value === "transparent") {
    return "transparent — `.clear` and `Color.Transparent` already exist";
  }
  if (value.includes(",")) {
    return "composite value — no single-value equivalent";
  }
  return `unsupported value: ${value}`;
}

/**
 * `$color.text.on-primary` → `textOnPrimary`, `$spacing.4` → `s4`.
 *
 * A name starting with a digit is not an identifier on either platform, so it
 * takes its scale's letter. The letter is derived from the group rather than
 * hardcoded, so a new numeric scale does not need this function edited.
 */
function identifier(tokenName: string): { group: string; name: string } {
  const [group, ...rest] = tokenName.replace(DOLLAR_PREFIX, "").split(".");
  const raw = rest.join(".");
  const parts = raw.split(NAME_SEPARATORS).filter(Boolean);
  let ident =
    parts[0] +
    parts
      .slice(1)
      .map((p) => p[0].toUpperCase() + p.slice(1))
      .join("");
  if (LEADING_DIGIT.test(ident)) {
    ident = group[0] + ident;
  }
  return { group, name: ident };
}

function groupTypeName(group: string): string {
  return group
    .split("-")
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
}

interface Entry {
  dark?: Resolved;
  light: Resolved;
  name: string;
  themed: boolean;
}

function collectEntries(
  ast: Ast,
  only?: string[]
): {
  groups: Map<string, Entry[]>;
  skipped: { name: string; reason: string }[];
} {
  const byName = new Map(ast.tokens.map((t) => [t.token.name, t]));
  const modesOf = new Map(ast.collections.map((c) => [c.name, c.modes]));

  const groups = new Map<string, Entry[]>();
  const skipped: { name: string; reason: string }[] = [];

  for (const token of ast.tokens) {
    if (only && !only.includes(token.token.collection)) {
      continue;
    }
    const modes = modesOf.get(token.token.collection) ?? ["default"];
    const themed = modes.includes("light") && modes.includes("dark");
    const lightMode = themed ? "light" : "default";

    const light = classify(resolve(token.token.name, lightMode, byName));
    if (typeof light === "string") {
      skipped.push({ name: token.token.name, reason: light });
      continue;
    }

    let dark: Resolved | undefined;
    if (themed) {
      const resolved = classify(resolve(token.token.name, "dark", byName));
      if (typeof resolved === "string") {
        skipped.push({ name: token.token.name, reason: resolved });
        continue;
      }
      dark = resolved;
    }

    const { group, name } = identifier(token.token.name);
    const entry: Entry = { dark, light, name, themed };
    const bucket = groups.get(group);
    if (bucket) {
      bucket.push(entry);
    } else {
      groups.set(group, [entry]);
    }
  }

  for (const entries of groups.values()) {
    entries.sort((a, b) => a.name.localeCompare(b.name));
  }
  return { groups, skipped };
}

function swiftValue(value: Resolved): string {
  if (value.kind === "curve") {
    return value.points.join(", ");
  }
  if (value.kind !== "color") {
    return `${value.value}`;
  }
  return value.alpha === 1
    ? `SwiftUI.Color(hex: 0x${value.hex})`
    : `SwiftUI.Color(hex: 0x${value.hex}, opacity: ${value.alpha})`;
}

function kotlinValue(value: Resolved): string {
  if (value.kind === "curve") {
    return `CubicBezierEasing(${value.points.map((p) => `${p}f`).join(", ")})`;
  }
  if (value.kind !== "color") {
    return `${value.value}`;
  }
  const alpha = toHex(value.alpha * 255);
  return `ComposeColor(0x${alpha}${value.hex})`;
}

function swiftIdentifier(name: string): string {
  return SWIFT_RESERVED.has(name) ? `\`${name}\`` : name;
}

/**
 * A single-mode token as a Swift constant — or, for an easing, a function.
 *
 * The scale decides the type. Every number was `CGFloat`, which made a
 * duration a length: `Duration.fast` was `0.15` points. It is seconds, which
 * is what `Animation` takes. An easing is a curve, and SwiftUI's curve type is
 * an `Animation` with a duration, so the token is a function of one.
 */
function swiftConstant(group: string, entry: Entry): string[] {
  const value = entry.light;
  const name = swiftIdentifier(entry.name);
  if (value.kind === "curve") {
    return [
      `        /// \`cubic-bezier(${value.points.join(", ")})\`, as \`.timingCurve\`.`,
      `        public static func ${name}(_ duration: TimeInterval) -> Animation {`,
      `            .timingCurve(${swiftValue(value)}, duration: duration)`,
      "        }",
    ];
  }
  if (group === "duration") {
    return [
      `        public static let ${name}: TimeInterval = ${swiftValue(value)}`,
    ];
  }
  // Qualified: this sits inside `enum Color`, where the bare name is the enum
  // rather than SwiftUI's type.
  const swiftType = value.kind === "color" ? "SwiftUI.Color" : "CGFloat";
  return [`        public static let ${name}: ${swiftType} = ${swiftValue(value)}`];
}

/**
 * The Kotlin counterpart. A duration is the `Int` of milliseconds `tween`
 * takes — it was `0.15.dp`, a fraction of a pixel — and an easing is Compose's
 * own `Easing`, aliased because the token group is also called that.
 */
function kotlinConstant(group: string, entry: Entry): string {
  const value = entry.light;
  if (value.kind === "curve") {
    return `        val ${entry.name}: ComposeEasing = ${kotlinValue(value)}`;
  }
  if (group === "duration" && value.kind === "number") {
    return `        val ${entry.name}: Int = ${Math.round(value.value * 1000)}`;
  }
  if (value.kind === "color") {
    return `        val ${entry.name}: ComposeColor = ${kotlinValue(value)}`;
  }
  return `        val ${entry.name}: Dp = ${kotlinValue(value)}.dp`;
}

function pascal(name: string): string {
  return name[0].toUpperCase() + name.slice(1);
}

function swiftBrandDeclarations(brands: MobileOptions["brands"]): string[] {
  if (!brands || brands.length === 0) {
    return [];
  }
  return [
    "/// The brand a token resolves for. The base is no brand: `interactive-primary`",
    "/// is neutral-950, and a brand is a theme laid over it. Read it from",
    "/// `@Environment(\\.cocsoBrand)` and pass it to the tokens and resolvers that",
    "/// take it; the app sets it once at its root.",
    "public enum CocsoBrand: Sendable {",
    "    case base",
    ...brands.map((b) => `    case ${b.name}`),
    "}",
    "",
    "private struct CocsoBrandKey: EnvironmentKey {",
    "    static let defaultValue: CocsoBrand = .base",
    "}",
    "",
    "public extension EnvironmentValues {",
    "    var cocsoBrand: CocsoBrand {",
    "        get { self[CocsoBrandKey.self] }",
    "        set { self[CocsoBrandKey.self] = newValue }",
    "    }",
    "}",
    "",
  ];
}

function kotlinBrandDeclarations(brands: MobileOptions["brands"]): string[] {
  if (!brands || brands.length === 0) {
    return [];
  }
  return [
    "/**",
    " * The brand a token resolves for. The base is no brand: `interactive-primary`",
    " * is neutral-950, and a brand is a theme laid over it. Brand-aware tokens read",
    " * `LocalCocsoBrand` themselves, so no call site changes — the app provides it",
    " * once at its root.",
    " */",
    "enum class CocsoBrand {",
    "    Base,",
    ...brands.map((b) => `    ${pascal(b.name)},`),
    "}",
    "",
    "val LocalCocsoBrand = compositionLocalOf { CocsoBrand.Base }",
    "",
  ];
}

/** One themed Swift token, with a brand axis when any brand overrides it. */
function swiftThemedFunction(
  entry: Entry,
  brands: MobileOptions["brands"]
): string[] {
  const dark = entry.dark ?? entry.light;
  const base = `scheme == .dark ? ${swiftValue(dark)} : ${swiftValue(entry.light)}`;
  const branded = (brands ?? []).filter((b) => b.overrides.has(entry.name));
  if (branded.length === 0) {
    // When brands exist every themed token takes the axis, so a resolver can
    // pass `brand:` uniformly; a token no brand overrides ignores it.
    const axis = brands?.length ? ", brand _: CocsoBrand = .base" : "";
    return [
      `        public static func ${entry.name}(_ scheme: ColorScheme${axis}) -> SwiftUI.Color {`,
      `            ${base}`,
      "        }",
    ];
  }
  // A brand-aware token. The default keeps every existing call site compiling
  // and rendering the base; a view that reads the brand from its environment
  // passes it through.
  return [
    `        public static func ${entry.name}(`,
    "            _ scheme: ColorScheme,",
    "            brand: CocsoBrand = .base",
    "        ) -> SwiftUI.Color {",
    "            switch brand {",
    ...branded.map(
      (b) =>
        `            case .${b.name}: return CocsoBrand${pascal(b.name)}.Color.${entry.name}(scheme)`
    ),
    `            default: return ${base}`,
    "            }",
    "        }",
  ];
}

/** One themed Kotlin token; brand-aware ones read `LocalCocsoBrand` themselves. */
function kotlinThemedFunction(
  entry: Entry,
  brands: MobileOptions["brands"]
): string[] {
  const dark = entry.dark ?? entry.light;
  const base = `if (isSystemInDarkTheme()) ${kotlinValue(dark)} else ${kotlinValue(entry.light)}`;
  const branded = (brands ?? []).filter((b) => b.overrides.has(entry.name));
  if (branded.length === 0) {
    return [
      "        @Composable",
      "        @ReadOnlyComposable",
      `        fun ${entry.name}(): ComposeColor =`,
      `            ${base}`,
    ];
  }
  // No call site changes — the app provides `LocalCocsoBrand` once at its root.
  return [
    "        @Composable",
    "        @ReadOnlyComposable",
    `        fun ${entry.name}(): ComposeColor = when (LocalCocsoBrand.current) {`,
    ...branded.map(
      (b) =>
        `            CocsoBrand.${pascal(b.name)} -> CocsoBrand${pascal(b.name)}.Color.${entry.name}()`
    ),
    `            else -> ${base}`,
    "        }",
  ];
}

function generateSwift(ast: Ast, options: MobileOptions): string {
  const { groups } = collectEntries(ast, options.only);
  const type = options.typeName ?? "CocsoTokens";
  const lines = [
    HEADER,
    "",
    "import SwiftUI",
    "",
    "private extension Color {",
    "    init(hex: UInt32, opacity: Double = 1) {",
    "        self.init(",
    "            .sRGB,",
    "            red: Double((hex >> 16) & 0xFF) / 255,",
    "            green: Double((hex >> 8) & 0xFF) / 255,",
    "            blue: Double(hex & 0xFF) / 255,",
    "            opacity: opacity",
    "        )",
    "    }",
    "}",
    "",
    ...(type === "CocsoTokens" ? swiftBrandDeclarations(options.brands) : []),
    `public enum ${type} {`,
  ];

  for (const [group, entries] of groups) {
    const name = groupTypeName(group);
    lines.push(`    public enum ${name} {`);

    // Per token, not per group. The raw ramps share the `color` group with the
    // semantic layer but have one value, and wrapping them in a scheme
    // parameter would ask a caller to answer a question the token does not
    // have — as well as hiding that a ramp is the same in both themes, which
    // is what lets an app override one.
    for (const entry of entries.filter((e) => !e.themed)) {
      lines.push(...swiftConstant(group, entry));
    }

    const themed = entries.filter((e) => e.themed);
    if (themed.length > 0) {
      lines.push(
        "",
        "        /// Resolved against the view's colour scheme. Read these as",
        "        /// `CocsoTokens.Color.textPrimary(scheme)`, with `scheme` from",
        "        /// `@Environment(\\.colorScheme)`."
      );
      for (const entry of themed) {
        lines.push(...swiftThemedFunction(entry, options.brands));
      }
    }
    lines.push("    }", "");
  }

  lines.push("}", "");
  return lines.join("\n");
}

function generateKotlin(ast: Ast, options: MobileOptions): string {
  const { groups } = collectEntries(ast, options.only);
  const type = options.typeName ?? "CocsoTokens";
  const pkg = options.packageName ?? "ai.cocso.ui";
  const hasEasing = groups.has("easing");
  const lines = [
    HEADER,
    "",
    `package ${pkg}`,
    "",
    // Aliased for the same reason as `ComposeColor`: inside `object Easing`
    // the bare name is the token group.
    ...(hasEasing
      ? [
          "import androidx.compose.animation.core.CubicBezierEasing",
          "import androidx.compose.animation.core.Easing as ComposeEasing",
        ]
      : []),
    "import androidx.compose.runtime.Composable",
    "import androidx.compose.runtime.ReadOnlyComposable",
    "import androidx.compose.foundation.isSystemInDarkTheme",
    ...(type === "CocsoTokens" && options.brands?.length
      ? ["import androidx.compose.runtime.compositionLocalOf"]
      : []),
    // Aliased: these objects sit inside `object Color`, where the bare name is
    // the token group rather than Compose's type.
    "import androidx.compose.ui.graphics.Color as ComposeColor",
    "import androidx.compose.ui.unit.Dp",
    "import androidx.compose.ui.unit.dp",
    "",
    ...(type === "CocsoTokens" ? kotlinBrandDeclarations(options.brands) : []),
    `object ${type} {`,
  ];

  for (const [group, entries] of groups) {
    const name = groupTypeName(group);
    lines.push(`    object ${name} {`);

    for (const entry of entries.filter((e) => !e.themed)) {
      lines.push(kotlinConstant(group, entry));
    }

    const themed = entries.filter((e) => e.themed);
    if (themed.length > 0) {
      lines.push(
        "",
        "        // Resolved against the system theme, so a caller cannot render",
        "        // light tokens in a dark window by forgetting to pass a flag."
      );
      for (const entry of themed) {
        lines.push(...kotlinThemedFunction(entry, options.brands));
      }
    }
    lines.push("    }", "");
  }

  lines.push("}", "");
  return lines.join("\n");
}

export function generateMobileFromAst(
  ast: Ast,
  options: MobileOptions = {}
): MobileOutput {
  const { skipped } = collectEntries(ast, options.only);
  return {
    kotlin: generateKotlin(ast, options),
    skipped,
    swift: generateSwift(ast, options),
  };
}

export const mobile = {
  generateMobileFromAst,
} as const;
