import type { Ast, TokenDecl } from "../types";

/**
 * Swift and Kotlin token emitters.
 *
 * CSS can defer: `--cocso-color-text-primary: var(--cocso-color-neutral-950)`
 * leaves the indirection to the browser, and the dark theme redefines one end
 * of it. Neither platform here has that, so a token has to arrive as a value —
 * every reference chain resolved, once per mode.
 *
 * That is also why this lives beside the CSS emitters rather than in a script
 * that reads the YAML. `cocso/mobile` had such a script, and when the semantic
 * colours moved from one mode to two it did not fail: it kept reading
 * `values.default`, found nothing, and emitted four colours instead of
 * fifty-nine. Emitting from the validated AST means a token missing a value for
 * a mode its collection declares is rejected before it reaches here.
 */

export interface MobileOptions {
  /** Kotlin only. */
  packageName?: string;
  /** Swift: the enclosing type. Kotlin: the object name. */
  typeName?: string;
}

export interface MobileOutput {
  kotlin: string;
  /** Tokens deliberately not emitted, with the reason. */
  skipped: { name: string; reason: string }[];
  swift: string;
}

const HEADER = [
  "// Generated by @cocso-ui/baseframe — do not edit.",
  "// Source: packages/baseframe-sources",
  "// Regenerate: pnpm --filter @cocso-ui/baseframe generate:mobile",
].join("\n");

const TOKEN_REF = /^\$[a-z0-9-]+\./i;
const HEX = /^#([0-9a-f]{6})$/i;
const PX = /^(-?\d+(?:\.\d+)?)px$/;
const SECONDS = /^(-?\d+(?:\.\d+)?)s$/;
const PLAIN_NUMBER = /^-?\d+(?:\.\d+)?$/;
const NAME_SEPARATORS = /[.\-_]/;
const LEADING_DIGIT = /^\d/;
const DOLLAR_PREFIX = /^\$/;
const RGBA =
  /^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/;

function toHex(n: number): string {
  return Math.max(0, Math.min(255, Math.round(n)))
    .toString(16)
    .toUpperCase()
    .padStart(2, "0");
}

/** A value the platforms can hold, once every reference is followed. */
type Resolved =
  | { kind: "color"; hex: string; alpha: number }
  | { kind: "number"; value: number };

/**
 * Follow `$color.text.primary` → `$color.neutral-950` → `#131416`.
 *
 * A reference is resolved in the mode being emitted, falling back to `default`
 * — the ramps live in a single-mode collection, so a themed token reaching one
 * lands on its only value rather than failing to find a `light`.
 */
function resolve(
  name: string,
  mode: string,
  byName: Map<string, TokenDecl>,
  seen = new Set<string>()
): string | number | null {
  if (seen.has(name)) {
    throw new Error(`Circular token reference: ${[...seen, name].join(" → ")}`);
  }
  seen.add(name);

  const token = byName.get(name);
  if (!token) {
    return null;
  }
  const value =
    token.values.find((v) => v.mode === mode)?.value ??
    token.values.find((v) => v.mode === "default")?.value;
  if (value === undefined) {
    return null;
  }
  if (typeof value === "string" && TOKEN_REF.test(value)) {
    return resolve(value, mode, byName, seen);
  }
  return value;
}

function classify(value: string | number | null): Resolved | string {
  if (value === null) {
    return "unresolved reference";
  }
  if (typeof value === "number") {
    return { kind: "number", value };
  }
  const hex = value.match(HEX);
  if (hex) {
    return { alpha: 1, hex: hex[1].toUpperCase(), kind: "color" };
  }
  // Both platforms hold alpha in a colour perfectly well — SwiftUI takes an
  // opacity, Compose takes AARRGGBB. An earlier version of this file skipped
  // them and said neither could, which was not a fact about the platforms but
  // about the converter it replaced. Dropping them would take the whole
  // `overlay-*` role, whose entire job is a translucent tint, off mobile.
  const rgba = value.match(RGBA);
  if (rgba) {
    const [, r, g, b, a] = rgba;
    return {
      alpha: a === undefined ? 1 : Number(a),
      hex: toHex(Number(r)) + toHex(Number(g)) + toHex(Number(b)),
      kind: "color",
    };
  }
  const px = value.match(PX);
  if (px) {
    return { kind: "number", value: Number(px[1]) };
  }
  const seconds = value.match(SECONDS);
  if (seconds) {
    return { kind: "number", value: Number(seconds[1]) };
  }
  // YAML quotes some scales, so a plain number can arrive as a string.
  if (PLAIN_NUMBER.test(value)) {
    return { kind: "number", value: Number(value) };
  }
  if (value === "transparent") {
    return "transparent — `.clear` and `Color.Transparent` already exist";
  }
  if (value.includes(",")) {
    return "composite value — no single-value equivalent";
  }
  return `unsupported value: ${value}`;
}

/**
 * `$color.text.on-primary` → `textOnPrimary`, `$spacing.4` → `s4`.
 *
 * A name starting with a digit is not an identifier on either platform, so it
 * takes its scale's letter. The letter is derived from the group rather than
 * hardcoded, so a new numeric scale does not need this function edited.
 */
function identifier(tokenName: string): { group: string; name: string } {
  const [group, ...rest] = tokenName.replace(DOLLAR_PREFIX, "").split(".");
  const raw = rest.join(".");
  const parts = raw.split(NAME_SEPARATORS).filter(Boolean);
  let ident =
    parts[0] +
    parts
      .slice(1)
      .map((p) => p[0].toUpperCase() + p.slice(1))
      .join("");
  if (LEADING_DIGIT.test(ident)) {
    ident = group[0] + ident;
  }
  return { group, name: ident };
}

function groupTypeName(group: string): string {
  return group
    .split("-")
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
}

interface Entry {
  dark?: Resolved;
  light: Resolved;
  name: string;
  themed: boolean;
}

function collectEntries(ast: Ast): {
  groups: Map<string, Entry[]>;
  skipped: { name: string; reason: string }[];
} {
  const byName = new Map(ast.tokens.map((t) => [t.token.name, t]));
  const modesOf = new Map(ast.collections.map((c) => [c.name, c.modes]));

  const groups = new Map<string, Entry[]>();
  const skipped: { name: string; reason: string }[] = [];

  for (const token of ast.tokens) {
    const modes = modesOf.get(token.token.collection) ?? ["default"];
    const themed = modes.includes("light") && modes.includes("dark");
    const lightMode = themed ? "light" : "default";

    const light = classify(resolve(token.token.name, lightMode, byName));
    if (typeof light === "string") {
      skipped.push({ name: token.token.name, reason: light });
      continue;
    }

    let dark: Resolved | undefined;
    if (themed) {
      const resolved = classify(resolve(token.token.name, "dark", byName));
      if (typeof resolved === "string") {
        skipped.push({ name: token.token.name, reason: resolved });
        continue;
      }
      dark = resolved;
    }

    const { group, name } = identifier(token.token.name);
    const entry: Entry = { dark, light, name, themed };
    const bucket = groups.get(group);
    if (bucket) {
      bucket.push(entry);
    } else {
      groups.set(group, [entry]);
    }
  }

  for (const entries of groups.values()) {
    entries.sort((a, b) => a.name.localeCompare(b.name));
  }
  return { groups, skipped };
}

function swiftValue(value: Resolved): string {
  if (value.kind !== "color") {
    return `${value.value}`;
  }
  return value.alpha === 1
    ? `SwiftUI.Color(hex: 0x${value.hex})`
    : `SwiftUI.Color(hex: 0x${value.hex}, opacity: ${value.alpha})`;
}

function kotlinValue(value: Resolved): string {
  if (value.kind !== "color") {
    return `${value.value}`;
  }
  const alpha = toHex(value.alpha * 255);
  return `ComposeColor(0x${alpha}${value.hex})`;
}

function generateSwift(ast: Ast, options: MobileOptions): string {
  const { groups } = collectEntries(ast);
  const type = options.typeName ?? "CocsoTokens";
  const lines = [
    HEADER,
    "",
    "import SwiftUI",
    "",
    "private extension Color {",
    "    init(hex: UInt32, opacity: Double = 1) {",
    "        self.init(",
    "            .sRGB,",
    "            red: Double((hex >> 16) & 0xFF) / 255,",
    "            green: Double((hex >> 8) & 0xFF) / 255,",
    "            blue: Double(hex & 0xFF) / 255,",
    "            opacity: opacity",
    "        )",
    "    }",
    "}",
    "",
    `public enum ${type} {`,
  ];

  for (const [group, entries] of groups) {
    const name = groupTypeName(group);
    lines.push(`    public enum ${name} {`);

    // Per token, not per group. The raw ramps share the `color` group with the
    // semantic layer but have one value, and wrapping them in a scheme
    // parameter would ask a caller to answer a question the token does not
    // have — as well as hiding that a ramp is the same in both themes, which
    // is what lets an app override one.
    for (const entry of entries.filter((e) => !e.themed)) {
      // Qualified: this sits inside `enum Color`, where the bare name is the
      // enum rather than SwiftUI's type.
      const swiftType =
        entry.light.kind === "color" ? "SwiftUI.Color" : "CGFloat";
      lines.push(
        `        public static let ${entry.name}: ${swiftType} = ${swiftValue(entry.light)}`
      );
    }

    const themed = entries.filter((e) => e.themed);
    if (themed.length > 0) {
      lines.push(
        "",
        "        /// Resolved against the view's colour scheme. Read these as",
        "        /// `CocsoTokens.Color.textPrimary(scheme)`, with `scheme` from",
        "        /// `@Environment(\\.colorScheme)`."
      );
      for (const entry of themed) {
        const dark = entry.dark ?? entry.light;
        lines.push(
          `        public static func ${entry.name}(_ scheme: ColorScheme) -> SwiftUI.Color {`,
          `            scheme == .dark ? ${swiftValue(dark)} : ${swiftValue(entry.light)}`,
          "        }"
        );
      }
    }
    lines.push("    }", "");
  }

  lines.push("}", "");
  return lines.join("\n");
}

function generateKotlin(ast: Ast, options: MobileOptions): string {
  const { groups } = collectEntries(ast);
  const type = options.typeName ?? "CocsoTokens";
  const pkg = options.packageName ?? "ai.cocso.ui";
  const lines = [
    HEADER,
    "",
    `package ${pkg}`,
    "",
    "import androidx.compose.runtime.Composable",
    "import androidx.compose.runtime.ReadOnlyComposable",
    "import androidx.compose.foundation.isSystemInDarkTheme",
    // Aliased: these objects sit inside `object Color`, where the bare name is
    // the token group rather than Compose's type.
    "import androidx.compose.ui.graphics.Color as ComposeColor",
    "import androidx.compose.ui.unit.Dp",
    "import androidx.compose.ui.unit.dp",
    "",
    `object ${type} {`,
  ];

  for (const [group, entries] of groups) {
    const name = groupTypeName(group);
    lines.push(`    object ${name} {`);

    for (const entry of entries.filter((e) => !e.themed)) {
      const value =
        entry.light.kind === "color"
          ? kotlinValue(entry.light)
          : `${entry.light.value}.dp`;
      const kotlinType = entry.light.kind === "color" ? "ComposeColor" : "Dp";
      lines.push(`        val ${entry.name}: ${kotlinType} = ${value}`);
    }

    const themed = entries.filter((e) => e.themed);
    if (themed.length > 0) {
      lines.push(
        "",
        "        // Resolved against the system theme, so a caller cannot render",
        "        // light tokens in a dark window by forgetting to pass a flag."
      );
      for (const entry of themed) {
        const dark = entry.dark ?? entry.light;
        lines.push(
          "        @Composable",
          "        @ReadOnlyComposable",
          `        fun ${entry.name}(): ComposeColor =`,
          `            if (isSystemInDarkTheme()) ${kotlinValue(dark)} else ${kotlinValue(entry.light)}`
        );
      }
    }
    lines.push("    }", "");
  }

  lines.push("}", "");
  return lines.join("\n");
}

export function generateMobileFromAst(
  ast: Ast,
  options: MobileOptions = {}
): MobileOutput {
  const { skipped } = collectEntries(ast);
  return {
    kotlin: generateKotlin(ast, options),
    skipped,
    swift: generateSwift(ast, options),
  };
}

export const mobile = {
  generateMobileFromAst,
} as const;
