import { buildValidatedAst } from "../transforms";
import type { Ast, Collections, Token, TokenDecl } from "../types";
import { createVarName } from "./utils/naming";

/** Options for Tailwind CSS generation. */
export interface TailwindOptions {
  /** Optional comment banner prepended to the generated CSS output. */
  banner?: string;
  /** Design-system CSS variable prefix used to produce `var(--{prefix}-*)` references. */
  prefix?: string;
}

// Collections whose tokens are excluded from @theme (Tailwind handles spacing natively)
const SKIP_COLLECTIONS = new Set(["spacing"]);
const TOKEN_COLLECTION_REGEX = /^\$([^.]+)\./;

/**
 * Extracts the collection segment from a token name of the form `$collection.token`.
 * Returns `null` when the name does not match the expected pattern.
 */
function extractCollection(tokenName: string): string | null {
  const match = tokenName.match(TOKEN_COLLECTION_REGEX);
  return match ? match[1] : null;
}

/**
 * Builds the `@theme { }` block that maps unprefixed Tailwind CSS variables to
 * their design-system counterparts via `var(--{dsPrefix}-*)`.
 *
 * Tokens belonging to skipped collections (e.g. `spacing`) are omitted because
 * Tailwind v4 handles those natively.
 */
function createTheme(tokens: TokenDecl[], dsPrefix: string): string {
  const vars: string[] = [];
  const processed = new Set<string>();

  for (const token of tokens) {
    if (processed.has(token.token.name)) {
      continue;
    }
    processed.add(token.token.name);

    const collection = extractCollection(token.token.name);
    if (!collection || SKIP_COLLECTIONS.has(collection)) {
      continue;
    }

    // 2-layer: --color-white: var(--cocso-color-white)
    const twVar = createVarName(token.token.name);
    const dsVar = createVarName(token.token.name, dsPrefix);
    vars.push(`  ${twVar}: var(${dsVar});`);
  }

  return vars.length > 0 ? `@theme {\n${vars.join("\n")}\n}` : "";
}

/**
 * Returns the list of `@utility` rules that Tailwind v4 cannot auto-generate.
 *
 * Currently only `z-*` is required because `--z-index-*` is a non-standard
 * property name that Tailwind does not recognise automatically.
 */
function createUtilities(): string[] {
  // Only z-* is needed: --z-index-* is non-standard, Tailwind won't auto-generate
  // font-* and shadow-* are auto-generated by Tailwind v4 from --font-weight-* and --shadow-*
  return ["@utility z-* { z-index: --value(--z-index-*); }"];
}

/**
 * Generates a Tailwind CSS 4.0 configuration string from a validated AST.
 *
 * Emits one `@theme` block per collection followed by the shared `@utility`
 * declarations needed to bridge non-standard CSS property names.
 */
export function generateFromAst(ast: Ast, options: TailwindOptions): string {
  const { banner = "", prefix = "cocso" } = options;
  const { tokens, collections } = ast;
  const parts: string[] = [];

  if (banner) {
    parts.push(banner);
  }

  for (const collection of collections) {
    const collectionTokens = tokens.filter(
      (token) => token.token.collection === collection.name
    );

    const theme = createTheme(collectionTokens, prefix);
    if (theme) {
      parts.push(theme);
      parts.push("");
    }
  }

  const utilities = createUtilities();

  if (utilities.length > 0) {
    parts.push(...utilities);
    parts.push("");
  }

  return parts.join("\n");
}

/**
 * Validates and builds an AST from raw token data, then generates a Tailwind
 * CSS 4.0 configuration string.
 *
 * Combines `buildValidatedAst` and `generateFromAst` into a single call.
 */
export function generateTailwindCSS(
  tokens: Token[],
  collections: Collections,
  options: TailwindOptions = {}
): string {
  const ast = buildValidatedAst(tokens, collections);
  return generateFromAst(ast, options);
}

/** Grouped entry point for Tailwind CSS generation utilities. */
export const tailwind = {
  generateTailwindCSS,
  generateFromAst,
  createVarName,
} as const;
