import type { RecipeDefinition, SlotStyles } from "@cocso-ui/recipe";
import { resolveForReact } from "@cocso-ui/recipe/resolvers/react";

/**
 * Convert camelCase to kebab-case: "bgColor" -> "bg-color"
 */
function camelToKebab(str: string): string {
  return str.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
}

/**
 * Get all variant combinations for a recipe as an array of objects.
 * e.g., [{ variant: "primary", size: "large", shape: "square" }, ...]
 */
export function getAllCombinations<
  V extends Record<string, Record<string, Partial<Record<S, SlotStyles>>>>,
  S extends string,
>(recipe: RecipeDefinition<V, S>): Record<string, string>[] {
  const dimensions = Object.entries(recipe.variants).map(([dim, values]) => ({
    dim,
    values: Object.keys(values as Record<string, unknown>),
  }));

  const combos: Record<string, string>[] = [];
  function walk(idx: number, current: Record<string, string>) {
    if (idx === dimensions.length) {
      combos.push({ ...current });
      return;
    }
    const { dim, values } = dimensions[idx];
    for (const val of values) {
      current[dim] = val;
      walk(idx + 1, current);
    }
  }
  walk(0, {});
  return combos;
}

/**
 * Build a BEM modifier string from a variant combination.
 * e.g., { variant: "primary", size: "large" } -> "--variant-primary--size-large"
 */
function bemModifiers(name: string, combo: Record<string, string>): string {
  return Object.entries(combo)
    .map(([dim, val]) => `${name}--${dim}-${val}`)
    .join(" ");
}

/**
 * Check if a compound variant's conditions match a given variant combination.
 */
function matchesCompound(
  conditions: Record<string, string | string[]>,
  combo: Record<string, string>,
): boolean {
  return Object.entries(conditions).every(([dim, expected]) => {
    if (Array.isArray(expected)) {
      return expected.includes(combo[dim]);
    }
    return combo[dim] === expected;
  });
}

/**
 * Generate a CSS selector for a variant combination + optional state.
 */
function cssSelector(
  name: string,
  combo: Record<string, string>,
  state?: string,
): string {
  const base = `.${name}`;
  const mods = Object.entries(combo)
    .map(([dim, val]) => `.${name}--${dim}-${val}`)
    .join("");
  const pseudo = state === "hover" ? ":hover" : state === "active" ? ":active" : state === "focus" ? ":focus-visible" : "";
  return `${base}${mods}${pseudo}`;
}

interface CSSRule {
  selector: string;
  properties: Record<string, string>;
  mediaQuery?: string;
}

/**
 * Generate CSS rules for a single recipe.
 * Uses resolveForReact at build time to get CSS values, then formats as CSS classes.
 */
export function generateCSS<
  V extends Record<string, Record<string, Partial<Record<S, SlotStyles>>>>,
  S extends string,
>(recipe: RecipeDefinition<V, S>): string {
  const name = `cocso-${recipe.name}`;
  const combos = getAllCombinations(recipe);
  const rules: CSSRule[] = [];
  const stateNames = recipe.states ? Object.keys(recipe.states) : [];

  for (const combo of combos) {
    // Resolve base state using existing resolver (perfect reuse)
    const resolved = resolveForReact(recipe, combo as Record<string, never>);
    // resolved keys are like "--cocso-button-bgColor", kebab-case them to "--cocso-button-bg-color"
    const properties: Record<string, string> = {};
    for (const [key, value] of Object.entries(resolved)) {
      properties[camelToKebab(key)] = value;
    }

    if (Object.keys(properties).length > 0) {
      rules.push({
        selector: cssSelector(name, combo),
        properties,
      });
    }

    // Resolve state overrides
    for (const state of stateNames) {
      const stateResolved = resolveForReact(recipe, combo as Record<string, never>, { state });
      const stateProps: Record<string, string> = {};

      for (const [key, value] of Object.entries(stateResolved)) {
        const kebabKey = camelToKebab(key);
        // Only include properties that differ from base
        if (properties[kebabKey] !== value) {
          stateProps[kebabKey] = value;
        }
      }

      if (Object.keys(stateProps).length > 0) {
        const isHover = state === "hover";
        rules.push({
          selector: cssSelector(name, combo, state),
          properties: stateProps,
          mediaQuery: isHover ? "(hover: hover) and (pointer: fine)" : undefined,
        });
      }
    }
  }

  // Also add compound variant overrides as their own rules
  // (already handled by resolveForReact, which applies compound variants)

  return formatCSS(rules);
}

function formatCSS(rules: CSSRule[]): string {
  const lines: string[] = [];
  lines.push("/* Generated by @cocso-ui/codegen — do not edit */");
  lines.push("");

  // Group media-query rules
  const normalRules = rules.filter((r) => !r.mediaQuery);
  const mediaGroups = new Map<string, CSSRule[]>();
  for (const rule of rules) {
    if (rule.mediaQuery) {
      const group = mediaGroups.get(rule.mediaQuery) ?? [];
      group.push(rule);
      mediaGroups.set(rule.mediaQuery, group);
    }
  }

  for (const rule of normalRules) {
    lines.push(`${rule.selector} {`);
    for (const [prop, value] of Object.entries(rule.properties)) {
      lines.push(`  ${prop}: ${value};`);
    }
    lines.push("}");
    lines.push("");
  }

  for (const [query, groupRules] of mediaGroups) {
    lines.push(`@media ${query} {`);
    for (const rule of groupRules) {
      lines.push(`  ${rule.selector} {`);
      for (const [prop, value] of Object.entries(rule.properties)) {
        lines.push(`    ${prop}: ${value};`);
      }
      lines.push("  }");
      lines.push("");
    }
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate a className composition function for a recipe.
 * For single-slot: returns a string.
 * For multi-slot: returns an object with slot keys.
 */
export function generateRuntime<
  V extends Record<string, Record<string, Partial<Record<S, SlotStyles>>>>,
  S extends string,
>(recipe: RecipeDefinition<V, S>): string {
  const name = `cocso-${recipe.name}`;
  const dims = Object.entries(recipe.variants).map(([dim, values]) => ({
    dim,
    values: Object.keys(values as Record<string, unknown>),
  }));
  const defaults = recipe.defaultVariants ?? {};
  const isSingleSlot = recipe.slots.length === 1;

  const lines: string[] = [];
  lines.push("/* Generated by @cocso-ui/codegen — do not edit */");
  lines.push("");

  // Generate the props type
  const typeName = pascalCase(recipe.name) + "VariantProps";
  lines.push(`export interface ${typeName} {`);
  for (const { dim, values } of dims) {
    const unionType = values.map((v) => `"${v}"`).join(" | ");
    const defaultVal = (defaults as Record<string, string>)[dim];
    const isOptional = defaultVal !== undefined;
    lines.push(`  ${dim}${isOptional ? "?" : ""}: ${unionType};`);
  }
  lines.push("}");
  lines.push("");

  if (isSingleSlot) {
    // Single-slot: function returns string
    lines.push(`export function ${recipe.name}(props: ${typeName} = {}): string {`);
    lines.push(`  const {`);
    for (const { dim } of dims) {
      const defaultVal = (defaults as Record<string, string>)[dim];
      if (defaultVal) {
        lines.push(`    ${dim} = "${defaultVal}",`);
      } else {
        lines.push(`    ${dim},`);
      }
    }
    lines.push(`  } = props;`);
    lines.push(`  return \`${name}`);
    for (const { dim } of dims) {
      lines.push(`    \${${dim} ? \` ${name}--${dim}-\${${dim}}\` : ""}`);
    }
    lines.push(`  \`.trim().replace(/\\s+/g, " ");`);
    lines.push("}");
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * Generate TypeScript type declarations for a recipe.
 */
export function generateTypes<
  V extends Record<string, Record<string, Partial<Record<S, SlotStyles>>>>,
  S extends string,
>(recipe: RecipeDefinition<V, S>): string {
  const dims = Object.entries(recipe.variants).map(([dim, values]) => ({
    dim,
    values: Object.keys(values as Record<string, unknown>),
  }));
  const defaults = recipe.defaultVariants ?? {};

  const lines: string[] = [];
  lines.push("/* Generated by @cocso-ui/codegen — do not edit */");
  lines.push("");

  const typeName = pascalCase(recipe.name) + "VariantProps";
  lines.push(`export interface ${typeName} {`);
  for (const { dim, values } of dims) {
    const unionType = values.map((v) => `"${v}"`).join(" | ");
    const defaultVal = (defaults as Record<string, string>)[dim];
    const isOptional = defaultVal !== undefined;
    lines.push(`  ${dim}${isOptional ? "?" : ""}: ${unionType};`);
  }
  lines.push("}");
  lines.push("");

  // Export individual type aliases for convenience
  for (const { dim, values } of dims) {
    const typeName = pascalCase(recipe.name) + pascalCase(dim);
    const unionType = values.map((v) => `"${v}"`).join(" | ");
    lines.push(`export type ${typeName} = ${unionType};`);
  }
  lines.push("");

  lines.push(`export declare function ${recipe.name}(props?: ${typeName}): string;`);
  lines.push("");

  return lines.join("\n");
}

function pascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
}
