export const spacing = {
  s0: 'var(--ds-spacing-0)',
  s1: 'var(--ds-spacing-1)',
  s2: 'var(--ds-spacing-2)',
  s3: 'var(--ds-spacing-3)',
  s4: 'var(--ds-spacing-4)',
  s5: 'var(--ds-spacing-5)',
  s6: 'var(--ds-spacing-6)',
  s7: 'var(--ds-spacing-7)',
  s8: 'var(--ds-spacing-8)',
  s9: 'var(--ds-spacing-9)',
  s10: 'var(--ds-spacing-10)',
  s11: 'var(--ds-spacing-11)',
  s12: 'var(--ds-spacing-12)',
  s13: 'var(--ds-spacing-13)',
  s14: 'var(--ds-spacing-14)',
  s15: 'var(--ds-spacing-15)',
  s16: 'var(--ds-spacing-16)',
  s17: 'var(--ds-spacing-17)',
  s18: 'var(--ds-spacing-18)',
  s19: 'var(--ds-spacing-19)',
  s20: 'var(--ds-spacing-20)',
  s21: 'var(--ds-spacing-21)',
  max: 'var(--ds-spacing-max)',
} as const;
