/** Spacing token scale from s0 (0) to max (80px). */
export const spacing = {
  s0: "var(--cocso-spacing-0)",
  s1: "var(--cocso-spacing-1)",
  s2: "var(--cocso-spacing-2)",
  s3: "var(--cocso-spacing-3)",
  s4: "var(--cocso-spacing-4)",
  s5: "var(--cocso-spacing-5)",
  s6: "var(--cocso-spacing-6)",
  s7: "var(--cocso-spacing-7)",
  s8: "var(--cocso-spacing-8)",
  s9: "var(--cocso-spacing-9)",
  s10: "var(--cocso-spacing-10)",
  s11: "var(--cocso-spacing-11)",
  s12: "var(--cocso-spacing-12)",
  s13: "var(--cocso-spacing-13)",
  s14: "var(--cocso-spacing-14)",
  s15: "var(--cocso-spacing-15)",
  s16: "var(--cocso-spacing-16)",
  s17: "var(--cocso-spacing-17)",
  s18: "var(--cocso-spacing-18)",
  s19: "var(--cocso-spacing-19)",
  s20: "var(--cocso-spacing-20)",
  s21: "var(--cocso-spacing-21)",
  max: "var(--cocso-spacing-max)",
} as const;
