/**
 * Writes the SwiftUI and Compose style resolvers from the recipes.
 *
 * The recipes are the same ones the CSS comes from, so a variant added there
 * reaches all three platforms rather than three people remembering to add it.
 *
 *   pnpm --filter @cocso-ui/codegen generate:mobile
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { mkdirpSync } from "fs-extra";
import { generateRecipeStyles, type RecipeLike } from "../src/mobile-recipes";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "../../..");
const recipesDir = path.join(repoRoot, "packages/recipe/src/recipes");

const targets = {
  kotlin: path.join(
    repoRoot,
    "packages/compose/src/main/kotlin/ai/cocso/ui/CocsoStyles.kt"
  ),
  swift: path.join(repoRoot, "packages/swiftui/Sources/CocsoUI/CocsoStyles.swift"),
};

const HEADER = [
  "// Generated by @cocso-ui/codegen — do not edit.",
  "// Source: packages/recipe/src/recipes",
  "// Regenerate: pnpm --filter @cocso-ui/codegen generate:mobile",
].join("\n");

/**
 * Which colour tokens resolve against the theme rather than being constants.
 * Read from the published dark theme, which carries exactly the semantic layer.
 */
function themedColorNames(): Set<string> {
  const css = readFileSync(
    path.join(repoRoot, "packages/css/theme-dark.css"),
    "utf-8"
  );
  const names = new Set<string>();
  for (const [, name] of css.matchAll(/--cocso-color-([a-z0-9-]+):/g)) {
    const parts = name.split("-");
    names.add(
      parts[0] +
        parts
          .slice(1)
          .map((p) => p[0].toUpperCase() + p.slice(1))
          .join("")
    );
  }
  return names;
}

const recipes: RecipeLike[] = [];
for (const file of readdirSync(recipesDir).filter((f) =>
  f.endsWith(".recipe.ts")
)) {
  const module = await import(path.join(recipesDir, file));
  for (const value of Object.values(module)) {
    const candidate = value as RecipeLike;
    if (candidate?.name && candidate?.variants) {
      recipes.push(candidate);
    }
  }
}
recipes.sort((a, b) => a.name.localeCompare(b.name));

const output = generateRecipeStyles(recipes, themedColorNames());

const swift = [
  HEADER,
  "",
  "import SwiftUI",
  "",
  output.swift,
].join("\n");

const kotlin = [
  HEADER,
  "",
  "package ai.cocso.ui",
  "",
  "import androidx.compose.runtime.Composable",
  "import androidx.compose.runtime.ReadOnlyComposable",
  "import androidx.compose.ui.graphics.Color as ComposeColor",
  "import androidx.compose.ui.text.font.FontWeight",
  "import androidx.compose.ui.unit.Dp",
  "import androidx.compose.ui.unit.dp",
  "",
  output.kotlin,
].join("\n");

mkdirpSync(path.dirname(targets.swift));
mkdirpSync(path.dirname(targets.kotlin));
writeFileSync(targets.swift, swift);
writeFileSync(targets.kotlin, kotlin);
console.log(`wrote ${path.relative(repoRoot, targets.swift)}`);
console.log(`wrote ${path.relative(repoRoot, targets.kotlin)}`);
console.log(`${recipes.length} recipes`);

// Named, never silent — the same rule the token generator follows.
if (output.skipped.length > 0) {
  // One line per property, and a count that matches the lines. A property
  // refused in several variant layers is one decision, not several.
  const seen = new Map<string, string>();
  for (const { property, recipe, reason } of output.skipped) {
    const key = `${recipe}.${property}`;
    if (!seen.has(key)) {
      seen.set(key, reason);
    }
  }
  console.log(`\nnot carried across (${seen.size}):`);
  for (const [key, reason] of seen) {
    console.log(`  ${key} — ${reason}`);
  }
}
