name: Changeset Check

on:
  pull_request:
    branches:
      - main

jobs:
  changeset-check:
    name: Changeset Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Check for Changeset
        run: bunx changeset status --since main
        continue-on-error: true

      - name: Comment PR
        uses: actions/github-script@v7
        if: failure()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Changeset이 필요합니다!**\n\n이 PR에는 버전 변경사항이 포함되어 있습니다. `bun run changeset`을 실행하여 변경사항을 문서화해주세요.\n\n자세한 내용은 [Changeset 사용법](./CHANGESET_USAGE.md)을 참고하세요.'
            })
