name: Changeset Check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  changeset-check:
    name: Changeset Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Ensure main is fetched
        run: |
          git fetch origin main:refs/remotes/origin/main --update-head-ok || true
          echo "HEAD: $(git rev-parse --short HEAD)"
          echo "origin/main: $(git rev-parse --short origin/main)"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Check for Changeset
        id: changeset
        run: |
          set +e
          bunx changeset status --since origin/main
          exit_code=$?
          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Comment PR when missing changeset
        if: ${{ steps.changeset.outputs.exit_code != '0' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **Changeset required!**\n\nThis PR introduces version-affecting changes but does not include a changeset. Please run `bun run changeset` locally, commit the generated file, and push it to this branch.'
            })
